package.json, src/azure-account.api.d.ts, src/extension.ts, src/mongo/explorer.ts, src/mongo/mongo.ts
For now, this _only_ lists Mongo resources, and no other CosmosDB resources. I also removed the persistence of manually added connection strings because they were not using secure storage. I will add that support back in a future commit using secure storage.
Related issues: #10 #15
=> List Azure Resources in Mongo Explorer

src/mongo/languageClient.ts
Fix for #28 
In the Server class, `id` used to always be the connection string. However, when I added the Azure resources to the explorer, I refactored `id` and added a new `connectionString` field. Apparently I missed updating one of the fields. See here for the previous commit: https://github.com/Microsoft/vscode-cosmosdb/commit/3f5396480c5d2c06cc0ab2436ef8997dabdcceca#diff-566bee68995619b9ddea388ded5443caR162
=> Fix Mongo Scrapbook intellisense

.vscode/settings.json, package.json, src/commands.ts, src/extension.ts
This only supports the kind 'Mongo' and uses the same '+' icon as the 'Add Server' command. Both of these will have to be fixed in the future.
Related #11, #24
=> Add 'Create Cosmos DB Account' command

src/explorer.ts, src/extension.ts, src/nodes.ts
The location of the secure storage api might be moving around a little bit going forward, but the API itself shouldn't change much.
NOTE: We will not persist connection strings for resources from Azure. Those will be loaded on the fly each time. 
Related to #5
=> Persist attached mongo connection strings to secure storage

src/extension.ts
I broke a few commands when I added telemetry in #47. Apparently the typing of the async function was too specific
=> Fix commands failing with error 'getConnectionString is not a function'

src/commands.ts
this PR will make it such that when the user clicks away from the quick pick it won't go away and they dont have to start over.  see https://github.com/Microsoft/vscode-azureappservice/pull/43 for the equivalent in the app service extension.
=> use quickPickOptions.ignoreFocusOut

src/extension.ts
1. Using a warning message for now as ShowErrorMessage isn't working. 
2. Will look into allowing scrapbooks and prompting a file name only during save time.
=> Disp a warning message if working folder is absent.

src/mongo/nodes.ts, src/nodes.ts
Rather than popping up the vscode error message, display it right in the explorer.
Also, delay showing error messages for attached nodes until the user expands the node (rather than when the extension is activated)
Fixes #54
=> Display mongo server connection error in explorer

src/ErrorData.ts, src/docdb/commands.ts, src/extension.ts, src/util.ts
Fixes #96 
The activity ID is useful too, hence we are showing the whole error message in the output window.
=> DocumentDB creation/deletion errors - show full message in output window

src/extension.ts, src/utils/cp.ts
We could potentially output the connection string to the output window so the user can manually copy it, but I would prefer not to do that with a sensitive string.
Plus, it's easy to install xclip
Fixes #64
=> Show error when copying connection string on linux without xclip

src/extension.ts, src/mongo/commands.ts, src/util.ts
Fixes #68.
Uses the extension's folder path as a stand-in if no workspace has been opened yet.
Abandoning the previous PR.
=> Use context extensionpath if rootpath is null

src/docdb/nodes.ts, src/extension.ts, src/mongo/nodes.ts, src/nodes.ts
- Refactor LoadMore to src/nodes
- Change it a bit to stop at all 'falsey values' (cursors terminate at null). 
- Modifications to MongoCollectionNode's getChildren to implement LoadMore consistently.
=> Load More for Mongo Docs

src/mongo/commands.ts
There's no need to ask the user for id. Mongo will generate the it for us.
Fixes #124
=> Let Mongo auto-generate _id on new document

src/DocumentEditor.ts
On windows, one path started with 'C:\' and another started with 'c:\', so isLocalDocPath was returning false
However, I don't want to just make the check case-insensitive, because not all OS's are case-insensitive. Instead I use path.relative, which worked for me on mac, linux, and windows.
=> Fix 'Save' doesn't 'Update to Azure' on windows

src/docdb/commands.ts, src/mongo/commands.ts
Trim because ID's ending in space aren't allowed.
=> Allow empty strings for docID

package.json, src/docdb/commands.ts, src/docdb/nodes.ts, src/extension.ts, src/graph/graphNodes.ts, src/nodes.ts
This brings it up to parity with DocumentDB nodes:
1. Open in Portal
1. Refresh
1. Create/Delete database
1. Create/Delete graph
I think there's more code clean-up/organization that we could do, but I'll save that until after the release
=> Add right-click menu commands to graph nodes

src/DocumentEditor.ts, src/docdb/nodes.ts, src/extension.ts
Any time you expand a DocumentDB collection, you got an error like this:
It's because this.getPartitionKeyValue() relies on this.data, which wasn't set yet
=> Fix can't open documents in explorer

package.json
We're only allowed 5 keywords and Azure should be covered by our title/category
=> Remove Azure keyword

src/graph/GraphViewServer.ts, src/graph/GraphViewServerSocket.ts, src/graph/client/graphClient.ts, src/graph/client/graphTypes.ts
(For after Thursday release)
added graphTypes.ts.
As long as it's kept to just types and interfaces, they will be visible to the entire project and thus shared between client and server.
=> Share types between serve and client, add type safety to messages

resources/graphClient/graphClient.css, resources/graphClient/graphClient.html, src/graph/client/graphClient.ts
Code was setting text directly on #stats, thus erasing the span under it which is what the CSS keyed off of.  Be more explicit by adding another div.
=> Stats shouldn't display while querying

.travis.yml
The tests fail on osx most of the time and I think running tests on just linux is good enough for now
=> Remove osx from travis

.vscodeignore
This is used when creating a vsix. It actually doesn't affect the vsix size that much, but it's still the clean thing to do
=> Add vscodeignore

src/DocumentEditor.ts
Create a backup of the file before clearing it.
=> Changes to DocumentEditor dispose to improve VSCode restarting experience

package-lock.json, package.json, src/commands.ts, src/extension.ts, src/tree/CosmosDBAccountProvider.ts
Still working on the shared tree provider stuff. The diff on github doesn't work well for this PR for some reason haha - I suggest you use vscode or codeflow
Fixes #199 
Fixes #31 
I also ran into a bug where `client.databaseAccounts.createOrUpdate` returned an empty object every time. I switched away from the deprecated `azure-arm-documentdb` package to see if that would fix it, but it didn't. I left that work as a separate commit, but still included it in this PR. Fixes #90
=> Show creating node in explorer

src/mongo/tree/MongoAccountTreeItem.ts
This commit uses MongodB 3.6 docs specs to verify input when new
MongoDB is to be created:
https://docs.mongodb.com/manual/reference/limits/\#naming-restrictions
Thanks!
=> Add MongoDB database name validation. Closes #140

package.json, src/CosmosEditorManager.ts, src/constants.ts
1. Change it to a user setting
1. Clarify that it still uploads
Fixes #245 
Fixes #280 
This is consistent with the appservice experience implemented by Nathan here: https://github.com/Microsoft/vscode-azuretools/pull/43
=> Improve "Don't show again"

src/docdb/tree/DocDBDatabaseTreeItemBase.ts
The portal lists 1,000 as the lower limit (not 2,500)
This fixes it for graph and docdb (the graph tree item inherits from the docdbbase class). It does not fix it for mongo since that goes directly though the mongo api (aka not the cosmos api)
=> Default throughput to cheapest option

package.json
The current multi-group behavior probably isn't correct, and multiple settings don't make sense until we have filters anyway.
=> Restrict viewsettings to single array item for now

src/docdb/tree/DocDBDocumentTreeItem.ts
When you create the cheaper collection option in the portal, it doesn't let you specify a partition key.  These collections fail when the user tries to upload or delete a document. (I believe @StephenWeatherford ran into this issue when he attached his 'graph' account as a 'docdb' account and tried to update a document)
> Partition key provided either doesn't correspond to definition in the collection or doesn't match partition key field values specified in the document.
ActivityId: 164c2bd0-8118-46df-aafa-26eb376bf4f0, Microsoft.Azure.Documents.Common/1.19.121.4
Here's the docs for partition key:
http://azure.github.io/azure-documentdb-node/global.html#RequestOptions 
partitionKey | string | \<optional\> | Specifies a partition key definition for a particular path in the Azure DocumentDB …
=> Fix invalid partitionKey for cheap Cosmos collections

resources/graphClient/graphClient.css
Hard-coded watermark colors since they're against a hard-coded graph background.
=> Part of the requested UX changes, fixes #337

src/docdb/tree/DocDBAccountTreeItemBase.ts, src/docdb/tree/DocDBTreeItemBase.ts, src/graph/tree/GraphAccountTreeItem.ts, src/mongo/tree/MongoAccountTreeItem.ts, src/mongo/tree/MongoDatabaseTreeItem.ts, src/tree/AttachedAccountsTreeItem.ts
Ensures that on reloading VSCode, the attached emulator does not forget its emulator-ness.
=> Persist isEmulator for reload of VSCode, remove graph from quickpick

src/mongo/editors/MongoFindResultEditor.ts, src/mongo/languageClient.ts, src/mongo/registerMongoCommands.ts, src/mongo/services/languageService.ts, src/mongo/tree/MongoCollectionTreeItem.ts, src/mongo/tree/MongoDatabaseTreeItem.ts
Rather than trying to parse the connection string, just use `.db(databaseName)` after calling `MongoClient.connect`
This also ensure that connection strings that already have a database name will work:
>mongodb://examplemongo:xxx==@examplemongo.documents.azure.com:10255/**_admin_**?ssl=true
Let me know if you think it's worth merging before the release. I think it is, but I'm somewhat on the fence.
=> Make mongo connections simpler and more robust

src/docdb/tree/DocDBAccountTreeItem.ts, src/docdb/tree/DocDBAccountTreeItemBase.ts, src/docdb/tree/DocDBCollectionTreeItemBase.ts, src/docdb/tree/DocDBDatabaseTreeItem.ts, src/docdb/tree/DocDBDatabaseTreeItemBase.ts, src/docdb/tree/DocDBTreeItemBase.ts, src/graph/tree/GraphAccountTreeItem.ts, src/graph/tree/GraphDatabaseTreeItem.ts, src/mongo/tree/MongoAccountTreeItem.ts, src/tree/CosmosDBAccountProvider.ts
We weren't passing isEmulator in all cases, leading to bug #344. I made it a required parameter in the constructor to fix the issue
Fixes #344
=> Ensure isEmulator is always passed to child resources

package.json, src/commands/createCosmosDBAccount.ts
Unfortunately, this requires a new version of the cosmosdb SDK built using the current swagger, and it has lots of changes.  Not sure how high a risk it is to take this right now.
=> EnableGremlin capability to create post-GA graphs, fixes #352

package.json
Changed to dark grey to match the theme and better show off the icon.
Closes #359
=> Update the banner color to improve icon contrast.

src/CosmosEditorManager.ts
=> Regression fix: Check if globalState has the persisted editors before attempting to load

package.json
Would like to start adding alpha to the versions until we're ready to release. Will especially help telemetry to distinguish between 1.0 when it's the released version 1.0 and 1.0 when it's one day before preparing for the 1.1 release.
The alpha should always be the next incremental update so we don't have to worry about going backwards in version if we decide to do 5.2 instead of 6.0. Thus assuming 5.2 for now. We can still always release as 6.0 if desired.
=> Move to alpha version for next release

package.json
Fixes #311 
Removed the isExecutable flag because:
1) It keeps the settings from being allowed as a workspace setting (change in scope is not needed)
2) At least one customer is using this setting in a way that it's an executable (with no path) plus arguments
3) This flag is currently used in vscode only to keep it from being a workspace setting. Perhaps in the future they might add intellisense to it, but if people aren't using it as a full path anyway...
#
=> Allow mongo.shell.path to be a workspace setting

package.json, src/commands/deleteCosmosDBAccount.ts, src/graph/gremlinEndpoints.ts, src/tree/CosmosDBAccountProvider.ts, src/tree/CosmosDBAccountWizard/CosmosDBAccountNameStep.ts, src/tree/CosmosDBAccountWizard/CosmosDBAccountStep.ts
A new version of the cosmosdb package was released a few days ago that broke our builds. To fix it, I hard-coded the version of the package in this PR: https://github.com/Microsoft/vscode-cosmosdb/pull/496/files
This PR implements the _proper_ fix so that we can stay up to date. I'm fine merging this now or holding off until after the release. Let me know what you think
For more info, they changed this:
```typescript
declare class CosmosDBManagementClient extends AzureServiceClient {
```
(in javascript):
```
class CosmosDBManagementClient extends ServiceClient {
...
module.exports = CosmosDBManagementClient;
```
to this:
```
export default class CosmosDBManagementClient extends AzureServiceClient {
```
(in javascript):
```
class CosmosDBManagementClient extends ServiceClient {
... …
```
=> Fix build to work with latest cosmosdb package

src/mongo/languageClient.ts
In preparation for [Visual Studio Live Share](http://aka.ms/vsls) adding support for "guests" to receive remote language services for MongoDB, this PR simply updates the current `DocumentSelector` to be limited to `file` and `untitled` (unsaved) files. This way, when someone has this extension installed, and joins a Live Share session (where files use the `vsls:` scheme), their language services will be entirely derived from the remote/host side, which provides a more accurate and project-wide experience (guests in Live Share don't have local file access to the project they're collaborating with)
=> Restricting language services to local files

src/docdb/editors/DocDBDocumentNodeEditor.ts, src/mongo/editors/MongoCollectionNodeEditor.ts, src/mongo/editors/MongoDocumentNodeEditor.ts, src/utils/vscodeUtils.ts
Noticed that the previous implementation was guilty with the strictNullCheck flag. 
Remove almost-duplicate code in those files to reduce number of offending lines. In the process, this function is strictNullCheck compliant. :)
=> Remove duplicate code in editor node labels

package.json, src/mongo/editors/MongoCollectionNodeEditor.ts, src/mongo/editors/MongoDocumentNodeEditor.ts, src/mongo/editors/MongoFindOneResultEditor.ts, src/mongo/editors/MongoFindResultEditor.ts
Fixes #564 
Fixes #534 
Tested: 
ObjectID, nested ObjectID array, ISODate, sampleTime, minKey, MaxKey, undefined, numberLong, numberDecimal.
More types [here](https://docs.mongodb.com/manual/reference/mongodb-extended-json/#bson-data-types-and-associated-representations)
=> Mongo Editors:Use Ext JSON (EJSON) instead of JSON

src/docdb/registerDocDBCommands.ts
Called the wrong function in execute command. 
I let open Stored Procedure be a separate function since the open Document command is now starting to have many if else's, and I didn't want to add to the code smell.
=> Open Stored Procedure once created. Fixes #578

src/docdb/tree/DocDBStoredProceduresTreeItem.ts
No more changes. Verifying the name is in another work item that been deemed lower priority atm.
=> Change create stored procedure dialog Fixes #573

src/mongo/editors/MongoFindOneResultEditor.ts, src/mongo/tree/MongoCollectionTreeItem.ts
Fixes #608 
The beast of JSON.parse runs deep. :P  findOne is the only command which uses this `MongoCollectionTreeItem` while also requiring EJSON support. Hence that's the only function which uses `EJSON.stringify` rather than `this.stringify`.
=> MongoCollectionTreeItem: fix findOne's result to recognize ObjectIDs

thirdpartynotices.txt
Fixes #629 
PS : [line 244](https://github.com/Microsoft/vscode-cosmosdb/blob/3c572d376e1c5e6adffe6073a052ef23c370e2cc/thirdpartynotices.txt#L243) has filler text, but is in line with [mongodb's own license.txt](https://github.com/mongodb/mongo/blob/59f462046d76a7d8e48ec678ad03b489f5fcc56e/APACHE-2.0.txt#L190). 
Opened a [PR in their repo](https://github.com/mongodb/mongo/pull/1244), will update this if they respond to that PR by EOD.
=> Update third party notices for mongodb-extended-json.

package.json, src/mongo/MongoCommand.ts, src/mongo/MongoScrapbook.ts, src/mongo/registerMongoCommands.ts, test/mongoGetCommand.test.ts
This displays scrapbook parse errors in the Errors pane.  Right now it's pretty ugly due to various error-handling issues, but I'm enabling it now because it makes it a lot easier to see those other problems.  We can easily disable before shipping if we need to but hopefully the others will be fixed first.
Depends on https://github.com/Microsoft/vscode-azuretools/pull/189
=> Show errors in the error list

src/tree/AttachedAccountsTreeItem.ts, test/attachedAccountsTreeItem.test.ts
Allow valid MongoDB connection string when attaching to a server.
Current code disallowed a connection string of the form `mongodb+srv://yourhost/`, even though it is a valid [MongoDB connection](https://docs.mongodb.com/manual/reference/connection-string/#standard-connection-string-format) string.
This pull request expands the validation code to allow connections that start with both `mongodb://` and `mongodb+srv://`.
Other places in the code base account for and correctly parse the +srv variant, such as the code that parses database name from the connection URL.
=> Allow valid MongoDB connection strings

src/mongo/tree/MongoCollectionTreeItem.ts, src/mongo/tree/MongoDocumentTreeItem.ts
Fixes #534, #664, #663 (dupes)
Case I've Tested : 
Create these documents in the portal - non ObjectID _id, _id being a number, _id is a string, _id is a boolean
Create standard documents in the portal (_id being an ObjectID). 
Perform collection and document updates.
=> Mongo- Doc&Coll - Remove ObjectID constructor from update operation

src/docdb/tree/DocDBStoredProcedureTreeItem.ts, src/docdb/tree/DocDBStoredProceduresTreeItem.ts, src/graph/registerGraphCommands.ts, src/graph/tree/GraphCollectionTreeItem.ts, src/graph/tree/GraphDatabaseTreeItem.ts, src/graph/tree/GraphTreeItem.ts
Fixes #422 
- The UX I'm implementing follows the portal. 
Extension: 
Portal: 
Leaving some comments at places I would like some clarification.
=> Display stored procedures in graphs

src/constants.ts, src/docdb/editors/DocDBDocumentNodeEditor.ts, src/docdb/tree/DocDBDocumentTreeItem.ts, src/mongo/editors/MongoCollectionNodeEditor.ts, src/mongo/editors/MongoDocumentNodeEditor.ts, src/mongo/editors/MongoFindOneResultEditor.ts, src/mongo/tree/MongoDocumentTreeItem.ts, src/utils/vscodeUtils.ts, test/documentLabel.test.ts, thirdpartynotices.txt
=> Document labels: use fields other than _id wherever possible

src/mongo/grammar/visitors.ts, src/mongo/services/completionItemProvider.ts, src/utils/azureUtils.ts
This was causing some exceptions in the language server (i.e. a value was undefined but we were checking it against null).  It's possible these were caused by the mismatched grammar, but either way this is a bad idea.
=> Fix comparing explicitly against null

package.json, src/constants.ts, src/docdb/tree/DocDBDocumentsTreeItem.ts, src/extension.ts, src/extensionVariables.ts, src/utils/vscodeUtils.ts
=> Add setting for document field labels

src/mongo/shell.ts, src/mongo/tree/MongoAccountTreeItem.ts, src/mongo/tree/MongoDatabaseTreeItem.ts, src/tree/AttachedAccountsTreeItem.ts
Related to #696, fixes #687, fixes #613, fixes #508
1) Use a URI-encoded form of the password in the emulator connection string
2) Tell shell to ignore invalid certificates for emulator (since the emulator certificate is self-signed)
=> Fix connecting to emulator via Mongo shell

src/mongo/services/completionItemProvider.ts
`converToCapped` is invalid. 
`convertToCapped` is valid
=> Fix typo in intellisense suggestion that leads to an invalid command.

src/docdb/tree/DocDBCollectionTreeItem.ts, src/docdb/tree/DocDBDatabaseTreeItemBase.ts, src/docdb/tree/DocDBStoredProcedureTreeItem.ts, src/graph/tree/GraphCollectionTreeItem.ts, src/mongo/languageClient.ts, src/mongo/registerMongoCommands.ts, src/mongo/services/completionItemProvider.ts, src/mongo/services/languageService.ts, src/mongo/services/mongoScript.ts, src/mongo/services/schemaService.ts
Nothing but syntactic simplification for linting, nevertheless I tested all corresponding functionalities.
Next one will be the use of "type" in SchemaService, but this one requires a bit more attention.
I understand you plan to rewrite graphClient, so I won't fix the issues on that one.
Mind that the changes to default exports are breaking if someone is using vscode-cosmosdb as a library (I don't even think that makes sense).
=> remove minor syntactic grand-fathered tslint issues

package.json
I followed https://github.com/Microsoft/vscode-docker/pull/525 and https://github.com/Microsoft/vscode-azureappservice/issues/627. It looks like the version bump is all we need to do, correct?
=> Bump up version of vscode-extension-telemetry

.vscode/launch.json, .vscode/tasks.json
Detail: https://code.visualstudio.com/Docs/editor/tasks
=> Task 2.0.0

src/docdb/docDBConnectionStrings.ts, test/docDBConnectionStrings.test.ts
Fixes https://github.com/Microsoft/vscode-cosmosdb/issues/952
Seems easy enough to allow whitespace before the propertyName
=> Be leniant of whitespace in docDB connection string

src/commands/api/pickTreeItem.ts
We're not using this directly as a part of the App Service Connections feature, but I believe this is the last "Not supported" part of the api. Plus I might start leveraging this in the Functions extension
=> Support 'DatabaseAccount' as resourceType in pickTreeItem api

src/commands/importDocuments.ts
Fixes #961. 
The vague error arises from showOpenDialog. Hence I'm performing a check and printing a better message instead.
=> askForDocuments - throw error if no workspace found

.gitignore, .vscodeignore, package-lock.json, package.json, resources/graphClient/graphClient.css, resources/graphClient/graphClient.html, webpack.config.js
Fixes #1043, fixes #1041, fixes #1040
1) Fix references to graphClient.js and d3. Only repros when packaged.
2) Fix color issues in vscode Insiders (they've removed --color and --background-color -> use --vscode-editor-{background,forecolor} instead)
=> fix graph execute when packaged

.vscode/settings.json, package-lock.json, package.json, src/commands/api/findTreeItem.ts, src/docdb/tree/DocDBCollectionTreeItem.ts, src/docdb/tree/DocDBTreeItemBase.ts, src/extension.ts, src/extensionVariables.ts, src/graph/tree/GraphCollectionTreeItem.ts, src/mongo/registerMongoCommands.ts, src/table/tree/TableAccountTreeItem.ts, src/tree/AttachedAccountsTreeItem.ts, src/tree/AzureAccountTreeItemWithAttached.ts, src/tree/CosmosDBAccountProvider.ts, src/tree/SubscriptionTreeItem.ts, src/utils/vscodeUtils.ts
I used Cosmos DB as a trial for https://github.com/microsoft/vscode-azuretools/pull/499. See that PR for more info on why this change is happening.
=> Move to latest tree that's friendlier to non-Azure scenarios

.vscode/tasks.json, README.md, package.json, src/mongo/tree/MongoCollectionTreeItem.ts, src/mongo/tree/MongoDatabaseTreeItem.ts, src/utils/InteractiveChildProcess.ts, src/utils/getWorkspaceConfiguration.ts
Fixes #1176 (not correctly capturing results from some queries)
Fixes #1149 (probably already fixed, but also testcase had bad mongo.shell.args setting)
Fixes #1115 (Increase default timeout)
Add mongo.shell.args to README
Don't choke on bad mongo.shell.{path,args} settings (these utilities can be used to fix all our settings, but I'm not doing it here)
Immediately after browsing to mongo.exe, the query would fail because we're using correctly path from determineShellPathOrCmd)
=> Fix some remaining mongo shell issues

CHANGELOG.md, src/constants.ts, src/mongo/connectToMongoClient.ts, src/mongo/tree/MongoAccountTreeItem.ts, src/tree/AttachedAccountsTreeItem.ts
Fixes #1137
Fixes #1000
Related to #706?
=> Added local Mongo connection debugging tips

src/mongo/services/schemaService.ts
In src/mongo/services/schemaService.ts:
---------------------------------------
private functions `setSchemaForDocument` and `setSchemaForDocumentProperty` both
make decisions based on the type of the passed value/document
being an object.
Unfortunately, in javascript,
```javascript
typeof null === 'object'
```
As a result, if a property or an array value has a value of `null`,
`setSchemaForDocument` will throw an error when calling `Object.keys(document)`
=> Detect null values in schemas

package-lock.json, src/mongo/tree/MongoDatabaseTreeItem.ts
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1222
Today, createCollection takes all arguments and stringifies them.  That leads to this valid Mongo query:
``` 
db.createCollection("teste", {
validator: {
jsonSchema: {
bsonType: "object",
required: ["teste1", "teste2"],
properties: {
teste1: {
bsonType: "string",
description: "Deve ser uma string"
},
teste2: {
bsonType: "string",
description: "Deve ser uma string"
},
}
}
}
})
```
Being inserted like this:
With my changes, it is inserted normally:
I don't think Azure supports validators yet: 
But it does work for a local database:
`db.getCollectionInfos({name: 'teste3'})`
=> Create Collections 📚 supports options in Mongo scrapbooks 📔

src/mongo/connectToMongoClient.ts, src/mongo/tree/MongoAccountTreeItem.ts
Azure MongoDB accounts need to have the name passed in for private endpoints.  To test this, you have to remote SSH into VS Code in a VM that is in the same VNET as the private IP.
=> Add ➕ appName to options to support private 🚫 IP 💻

src/extension.ts
When executing the "Copy Connection String" command from the Command Palette, there is no feedback that the operation succeeded. This is a little awkward as the developer isn't sure if anything has happened.
This is less of an issue on the right-click since we are accustomed to right-click actions being successful by virtue of the right click occurring without error. Since we don't distinguish between when a the connection string copy occurs via right-click vs command palette, I suggest that we always show a notification that the connection string copy has occurred successfully.
=> Add a confirmation message for copy connection string

src/commands/importDocuments.ts, src/mongo/MongoScrapbook.ts, src/mongo/tree/MongoCollectionTreeItem.ts, src/mongo/tree/MongoDatabaseTreeItem.ts, test/mongoGetCommand.test.ts
A workaround for this issue https://github.com/microsoft/vscode-cosmosdb/issues/1193
You can now use `getCollection` to retrieve collections with odd naming conventions.  The real solution is to edit the grammar file to understand [] notation.
`getCollection` doesn't work today because `getCollection().find()` was parsed with the command.name as find, and would enter that part of the conditional rather than attempting to execute the command.
=> Check for chaining before executing command

src/mongo/MongoScrapbook.ts, src/mongo/tree/MongoCollectionTreeItem.ts, test/mongoGetCommand.test.ts
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1096
The error was happening because ISODate was being handled the same as a Date object.  The string representation for a Date is `1975-07-23T04:10:00.000` as opposed to ISODate's `1975-07-23T04:10:00.000Z`.  So when Mongo inserted the date, it just assumed the timezone was whatever the computer's local timezone was set to.
Edit: Both `db.test.insert({ 'datetime': ISODate('1975-07-23T04:10:00') })` and `db.test.insert({ 'datetime': ISODate('1975-07-23T04:10:00Z') })` are valid timestrings.
=> Include ISODate 📆 for constructorCall 👷‍♀️📞 and handle appropriately

src/mongo/tree/MongoCollectionTreeItem.ts, src/mongo/tree/MongoDocumentTreeItem.ts
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1298
After updating Mongodb in package.json, updateOne doesn't support overwriting anymore.  On a save, the action that we are actually performing is `replaceOne` where we update the document as we upload the entire document (rather than just updating the documents with new properties).
=> updateOne to replaceOne

src/commands/importDocuments.ts
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1307
Despite the [documentation](https://docs.mongodb.com/manual/reference/method/db.collection.insertMany/)
```
The operation returns the following document:
{
"acknowledged" : true,
"insertedIds" : [
ObjectId("562a94d381cb9f1cd6eb0e1a"),
ObjectId("562a94d381cb9f1cd6eb0e1b"),
ObjectId("562a94d381cb9f1cd6eb0e1c")
]
``` 
`insertMany` returns a `Promise<InsertWriteOpResult>` which according to [THIS documentation](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#~insertWriteOpResult) says `insertedIds` is an Object (which explains the error).  The type files in the library agree with this. 
Most likely this came from updating the mongoDrivers and should be included in the patch release.
=> Iterate over parsedIds 🆔 as objects 📦 rather than array 

src/commands/importDocuments.ts
https://github.com/microsoft/vscode-cosmosdb/issues/1307 never would've happened if we just used the `collection.insertMany` method that has proper types
=> Simplify Mongo import logic

CHANGELOG.md, package-lock.json, package.json, src/mongo/languageClient.ts
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1334, with much help from @dbaeumer
> Couple of things:
> 
> - the --debug option is since a long time deprecated in Node and since VS Code moved to a new Electron version I guess it is not supported anymore.
> - never pass any debug options when in run mode. You basically always started the server in debug mode. If you would only do this when you actually run in debug the extension would still have worked when installed from the marketplace.
=> Fix error "Language client is not ready yet"

src/postgres/tree/PostgresSchemaTreeItem.ts, src/postgres/tree/PostgresTableTreeItem.ts, src/postgres/tree/PostgresTablesTreeItem.ts
Adding this so we can support functions & stored procs too (related: https://github.com/microsoft/vscode-cosmosdb/issues/1407)
I had trouble finding good icons for the tables group and for individual tables so I left them generic for now.
Before ➡️After
=> Add "Tables" tree item for Postgres

package.json, src/CosmosEditorManager.ts, src/extension.ts, src/postgres/commands/openPostgresFunction.ts, src/postgres/commands/registerPostgresCommands.ts, src/postgres/editors/PostgresFunctionEditor.ts, src/postgres/tree/PostgresDatabaseTreeItem.ts, src/postgres/tree/PostgresFunctionTreeItem.ts, src/postgres/tree/PostgresFunctionsTreeItem.ts, src/postgres/tree/PostgresServerTreeItem.ts, src/postgres/tree/PostgresTablesTreeItem.ts
The filename includes function name, server name, and schema name to uniquely identify functions. Otherwise, you couldn't open two functions named "test" from two different servers/schemas at the same time.
Related to https://github.com/microsoft/vscode-cosmosdb/issues/1407
=> Add support for editing & updating Postgres functions

src/postgres/tree/PostgresDatabaseTreeItem.ts
We lost our `clientConfig` verification when we changed to lazy loading tables & functions. This ensures that connection errors are handled appropriately (like getting the option to configure firewall instead of just an error about it)
=> Ensure client config is valid before creating Postgres database children

src/postgres/tree/PostgresFunctionsTreeItem.ts
These can't be edited and I don't see a reason to display 'em
=> Don't display Postgres system functions in tree view

src/postgres/commands/connectPostgresDatabase.ts
This fixes the "treeItem.refresh is not a function" error.
Also it made sense to me to open the file you connect to db from
=> Fix connecting to databases from the explorer context menu

src/constants.ts, src/postgres/commands/connectPostgresDatabase.ts, src/postgres/commands/createPostgresFunctionQuery.ts, src/postgres/commands/openPostgresFunction.ts, src/postgres/commands/registerPostgresCommands.ts
This changes the default query file name to "pg-query" and applies the codelens only to files with names that contain "pg-query" and end with ".sql" 
("pg-query" seemed like a more Postgres specific option than just "query")
I also changed the file name format for function queries opened via the tree view. It looked too busy to show the server name, schema, and "pg-query"
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1455
=> Prevent codelens from appearing in all '.sql' files

src/postgres/commands/executePostgresQuery.ts
The CSV is opened as a new, unsaved file. Here's an example of executing a create query followed by a select query:
=> Display Postgres query output as CSV

src/docdb/registerDocDBCommands.ts, src/mongo/registerMongoCommands.ts
Calling `treeView.reveal` on a newly created tree item would always lead to the error reported in https://github.com/microsoft/vscode-cosmosdb/issues/1368. Loading more on the parent tree item before revealing would solve the problem but that seemed cumbersome. And since revealing tree items didn't seem to be a prevalent design pattern in other extensions I opted to remove it here.
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1368
=> Don't reveal tree items after creating

src/constants.ts, src/docdb/tree/DocDBDocumentTreeItem.ts
Using an empty object as the partition key when one wasn't provided seemed to be causing the issue.
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1434
=> Use empty string for emptyPartitionKeyValue

src/tree/SubscriptionTreeItem.ts
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1343
Technically this issue only reproduces with Azure Cosmos MongoDB v3.6, which our extension does not create by default (it creates v3.2, we should probably look into that 😂)
But I didn't notice any adverse effects appending the query param to older MongoDB accounts, so I assume that this is easier solution because I didn't see any obvious indicators if the account is 3.2 or 3.6.  (CosmosAccountType: Non-Production for 3.6, but that property didn't exist on the 3.2 accounts)
=> Add query param retrywrite=false

src/postgres/IPostgresProceduresQueryRow.ts, src/postgres/tree/PostgresFunctionTreeItem.ts, src/postgres/tree/PostgresFunctionsTreeItem.ts
An error was happening because the syntax we were using to delete functions didn't always work. Parenthesis need to be included after the function name. And if the function has arguments, those need to be included as well
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1494
=> Add arguments when deleting Postgres functions

test/nightly/azureResourceGraph.test.ts, test/nightly/azureResourceMongoDB.test.ts, test/nightly/azureResourceSQL.test.ts
Forgot to update the nightly tests when we merged 'cosmosDB.createAccount' into 'azureDatabases.createServer'
=> Update tests for 'azureDatabases.createServer' (not including Postgres)

extension.bundle.ts, src/mongo/MongoScrapbook.ts, src/mongo/registerMongoCommands.ts, src/mongo/services/MongoCodeLensProvider.ts, test/mongoGetCommand.test.ts
Calling `executeCommandFromText` wouldn't preserve any whitespace so the line and column info for errors was wrong. And the `executeMongoCommand` rules in package.json should guarantee that there's always an active text editor when the command is called.
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/647
This also fixes the off by one error noted in the same issue: https://github.com/microsoft/vscode-cosmosdb/issues/647#issuecomment-424898870
=> Only use 'executeCommandFromActiveEditor' when executing mongo commands

resources/icons/dark/list-unordered.svg, resources/icons/light/list-unordered.svg, src/postgres/tree/PostgresFunctionsTreeItem.ts, src/postgres/tree/PostgresStoredProceduresTreeItem.ts, src/postgres/tree/PostgresTablesTreeItem.ts
I thought I would hate this but I kinda don't...
| old | new |
| - | - |
| <img width="155" alt="Screen Shot 2020-06-24 at 11 21 36 AM" src="https://user-images.githubusercontent.com/22795803/85611918-3946e900-b60d-11ea-86d9-db23f82ebf03.png"> | <img width="155" alt="Screen Shot 2020-06-24 at 11 20 26 AM" src="https://user-images.githubusercontent.com/22795803/85611942-3fd56080-b60d-11ea-9723-26b1a5e011c6.png"> |
The UI peeps suggested to reuse the elephant icon for the database node but I like the plain one better.
They also suggested to use this icon for columns <img width="46" alt="Screen Shot 2020-06-24 at 11 32 35 AM" src="https://user-images.githubusercontent.com/22795803/85613127-6942bc00-b60e-11ea-84af-bb0520a8c41c.png"> but I like what we already have.
Fixes …
=> Update Postgres icons 🐘👀

package.json, src/constants.ts, src/docdb/tree/DocDBTreeItemBase.ts, src/extensionVariables.ts, src/mongo/MongoShell.ts, src/mongo/tree/MongoCollectionTreeItem.ts, src/utils/workspacUtils.ts
I got the default batch size of 20 from the mongo default (https://docs.mongodb.com/manual/tutorial/configure-mongo-shell/index.html#change-the-mongo-shell-batch-size)
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1073
=> Add a setting to configure the Mongo shell batch size

extension.bundle.ts, src/mongo/mongoConnectionStrings.ts, test/mongoConnectionStrings.test.ts
I didn't want to always encode connection strings just in case they're already encoded. So this only encodes if an encoding-related error is thrown first.
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1209
=> Encode mongo connection strings as needed

package-lock.json, package.json, src/mongo/MongoScrapbook.ts, src/utils/vscodeUtils.ts
Instead of creating a "result-x.json" file every time you execute a command, this creates one "Scrapbook-results.txt" file and appends each result to that. The results of `find` and `findOne` will still display in their own files.
I opted to use ".txt" instead of ".json" because the appended results won't always be valid json. 
After running "Execute All":
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/607
Depends on https://github.com/microsoft/vscode-azuretools/pull/758
=> Display mongo command results in a single file

extension.bundle.ts, src/postgres/commands/copyConnectionString.ts, src/postgres/getClientConfig.ts, src/postgres/postgresConnectionStrings.ts, test/postgresConnectionStrings.test.ts
Fixes #1696 
To fix missing databaseName value for Client connections with connectionString.
=> Fix Postgres client connection with connection string

src/tree/CosmosDBAccountWizard/CosmosDBAccountCreateStep.ts
=> Mongodb account creation defaults to '3.6' version

src/docdb/tree/DocDBDocumentsTreeItem.ts
The existing release already accounts for importing documents without partition key. An error is thrown with specific partition key information when a document doesn't contain the required partition key. 
The only issue is with scenarios where the partition key paths array has only 1 element, such as "/a".
=> Fix for importing documents without partition key 

src/mongo/mongoConnectionStrings.ts, src/mongo/tree/MongoAccountTreeItem.ts, test/mongoConnectionStrings.test.ts
Fixes #1687 
1. Current validation in the extension doesn't include "#?" in the restricted characters list, but these chars are present in the portal:
2. There is an issue with adding and deleting "@" for a database name:
To fix this, encodeURIComponent(databaseName) is added to escape special characters in the databaseName
=> Updated Mongodb databaseName validation

src/postgres/getClientConfig.ts
Fixes #1766 
There is no immediate change to the root certificate but eventually BaltimoreCyberTrustRoot will be replaced with DigiCertGlobalRootG2. 
There is an option to add both the certs to the connection config. We can do this now and avoid sudden outages if and when the BaltimoreCyberTrustRoot will be replaced.
=> Updated Postgres connection certificates

src/postgres/commands/createPostgresServer/IPostgresServerWizardContext.ts, src/postgres/commands/createPostgresServer/steps/PostgresServerCreateStep.ts, src/postgres/commands/createPostgresServer/steps/PostgresServerSkuStep.ts, src/tree/AzureDBAPIStep.ts
This PR extends the create server wizard for Postgres to allow the user to select which SKU, vCore and storage configuration instead of the default value in the current wizard.
The list isn't exhaustive, but would cover most use cases.
=> Extend Create Server for Postgres wizard to select SKU

CHANGELOG.md
Currently looks like this on the build/release...
=> Fix CHANGELOG styling

.azure-pipelines/compliance/CredScanSuppressions.json
Nightly runs were failing due to CredScan picking up something in a test file. 
Failing run: https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=41976&view=results
=> Fix credscan

package-lock.json, package.json, src/DatabasesFileSystem.ts
`findItem` in AzExtFileSystemProvider is hard-coded to search `this._tree` whenever you call `findItem`.  Checking the code, the only time `this._tree` is checked is when `findItem` is called, so it makes sense to just not use the `super` method for Databases.
=> Fix opening files in fs by searching the proper tree

package-lock.json, package.json, src/AzureDBExperiences.ts
Fixes #2005 
The way the compiler is loading the constants is throwing things off here.  Having constants import and use constants can cause weirdness depending on when it's loaded.
In this case, we were seeing the tags were `undefined` because the experiences were being created before all of the tags were.  We could probably move things around and fix this, but it seems a bit too high-risk of breaking other things that import these constants.
=> Hardcode experience tags

package-lock.json, package.json, src/commands/api/pickTreeItem.ts, src/extension.ts
Also re-ordered some calls in extension.ts because they relied on AppResourceTreeItem to be defined on rgApi.
=> Fix broken build by removing unused code

package-lock.json, package.json, src/extension.ts, src/resolver/AppResolver.ts
Now that we have access to the rgApi, it's better to get the subNode from that tree provider rather than one that was being created exclusively just to be used by the Databases extension.
Can't actually remove it from the extensionVariables because the tests will complain.
=> Search for subNode on appResourceTree

extension.bundle.ts, package-lock.json, package.json, src/postgres/commands/configurePostgresFirewall.ts, src/postgres/tree/PostgresDatabaseTreeItem.ts, src/utils/getIp.ts, test/util/getIp.test.ts
Fixes CVE-2022-33987 by replacing the [`public-ip`](https://www.npmjs.com/package/public-ip) package with our own util function. 
The util function uses the same methods to get the public IP as the package which are:
1. DNS via OpenDNS
2. HTTPS request to public API
=> Replace public-ip with our own util to fix CVE-2022-33987

src/AzureDBExperiences.ts
Postgres Flexible Server is no longer in Preview.
https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/quickstart-create-server-portal
=> Remove Preview label for Postgres Flexible

src/commands/api/DatabaseTreeItemInternal.ts
Fixes #2091 
Probably just a mistake when integrating this extension with the v1 host api.
=> Fix revealing attached database

package.json
Command breaks if you select anything in the resources view before running the command. It might be nice to be able to tell registerCommand to just ignore selected items.
=> Remove Create Server command from workspace submenu

webpack.config.js
This [PR](https://github.com/microsoft/vscode-cosmosdb/commit/ded030361a652a5b753fbf2dd6fed6bd42cf9431) missed one instance of `getCoreNodeModule` which was causing the build to fail. CTI brought to my attention that there was no extension to download in our Pipelines 😅
=> Remove getCoreNodeModule from webpack config

src/azureAccountUtils.ts, src/postgres/commands/checkAuthentication.ts, src/postgres/getClientConfig.ts, src/postgres/tree/PostgresDatabaseTreeItem.ts, src/postgres/tree/PostgresServerTreeItem.ts, test/unit/getClientConfig.test.ts
When `getClientConfig` cannot create a username-password clientConfig, attempt to create an AzureAd clientConfig. For new users who have configured their Azure AD access, they won't need to enter their user name and password.
=> Add AzureAd ClientConfig

src/postgres/commands/checkAuthentication.ts, src/postgres/tree/PostgresDatabaseTreeItem.ts, src/postgres/tree/PostgresServerTreeItem.ts
`isFirewallRuleSet` should be a concept of the server tree item since it only collaborates with members of a server tree item.
=> Move isFirewallRuleSet to DatabaseServerTreeItem

src/postgres/commands/checkAuthentication.ts, src/postgres/getClientConfig.ts, src/postgres/tree/ClientConfigFactory.ts, src/postgres/tree/PostgresDatabaseTreeItem.ts, src/postgres/tree/PostgresServerTreeItem.ts, test/unit/getClientConfig.test.ts
`getClientConfig` is replaced by `getClientConfigs` which will now return all the client config objects that may work. Existing test cases for `getClientConfig` are rewritten to cover `getClientConfigs`. A new factory method is implemented to handle creating a working client config from a database tree item. The factory method will try all the "available" client configs and return the first one that actually works. A telemetry event is added to monitor the result of each client config test.
=> Automatic retry PostgreSQL available client configs

src/postgres/commands/configurePostgresFirewall.ts, src/utils/getIp.ts
Mitigates https://github.com/microsoft/vscode-cosmosdb/issues/2168
Based on my testing, the deleted function no longer work for getting IP. Besides, I get rid of the notification for getting public IP since it's supposed to be a quick operation and doesn't convey much useful information to user.
=> Delete a no-longer-working getIp function

src/docdb/tree/DocDBDocumentTreeItem.ts
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1732
The `_rid` property may contain '+' which won't work as expected since we need to put the id in query strings.
=> Fix bad DocDB document id

src/postgres/postgresConstants.ts, src/postgres/tree/ClientConfigFactory.ts, src/postgres/tree/PostgresDatabaseTreeItem.ts
resolves: https://github.com/microsoft/vscode-cosmosdb/issues/2179
Our old mechanism has a major flaw that it cannot guarantee getting the correct IP address visible to the database server. In the worst case, we may enter a dead loop as below:
1. Get IP from 3rd party services, named IP_0
2. Attempt to connect to database server, which sees a different IP address, named IP_1
3. IP_1 is not in the firewall rules
4. We prompt to add IP_0 to firewall rules, because this is the IP we assume we are using
5. We retry still get a firewall error
This PR let the extension stop trying to reconfigure it for the user if we have tested (and configured) it once. Instead, it directs the user to go to Azure Portal which ensures the correct IP address can be added to the firewall rules. In the network …
=> Stop dealing with IP address if it has been configured once

src/docdb/tree/DocDBDatabaseTreeItemBase.ts
resolves #2075.
We don't know the "serverless" property on the attached database accounts. The change work arounds that issue by letting people optionally skip setting the throughput property so they can create collections when the database account is serverless.
=> Mitigate unsupported throughput config

src/postgres/tree/ClientConfigFactory.ts, src/postgres/tree/PostgresServerTreeItem.ts
The original warning message is not 100% correct since Azure Portal doesn't guarantee that it can add the actual IP address to the firewall rules. The string is a slightly modified version of the Portal string indicating what to do for the next step.
=> Improve warning message on firewall error

package.json, src/constants.ts, src/docdb/registerDocDBCommands.ts, src/docdb/tree/DocDBCollectionTreeItem.ts, src/docdb/tree/DocDBTriggerTreeItem.ts, src/docdb/tree/DocDBTriggersTreeItem.ts
Supported features:
- list triggers of a cosmosDB collection
- create a trigger
- view/edit the function body of a trigger
- delete a trigger
=> feature: cosmosDB triggers basic support

src/commands/importDocuments.ts, src/postgres/commands/executePostgresQueryInDocument.ts
resolves: https://github.com/microsoft/vscode-cosmosdb/issues/2199
=> fix: fix timestamp in log output

package.json, src/extension.ts, src/extensionVariables.ts
There is almost no reason to not include the timestamp since it provides important information for filtering the relevant messages. I removed the setting that governs whether the output will include timestamp. Using the LogOutputChannel will always include the timestamp in each message. It also allows the developer to add verbose logging output that can be checked into code to simplify testing and debugging without affecting user experience.
=> chore: Use LogOutputChannel

src/mongo/commands/connectMongoDatabase.ts
`ext.rgApi.appResourceTree.findTreeItem()` is a very slow API. If the underlying connection hasn't changed, the change avoids re-searching the tree for the node to allow almost instantaneous execution of the MongoDB commands in the scrapbook if a matching connection already exists. Otherwise, every command execution will have to wait for several seconds.
It's possible for a user to delete a database, recreate a new one with the same name to masquerade the old database and thus invalidate the connection. I think it's a rare case and the user can work around it by clicking the connect button to re-connect.
=> perf: Use cached mongoDB connection

package.json, src/docdb/commands/viewDocDBCollectionOffer.ts, src/docdb/registerDocDBCommands.ts
resolves: https://github.com/microsoft/vscode-cosmosdb/issues/1979
The offer of a CosmosDB NoSQL collection will look like this:
```json
{
"resource": "dbs/xxx/colls/xxx/",
"offerType": "Invalid",
"offerResourceId": "xxx",
"offerVersion": "V2",
"content": {
"offerThroughput": 400,
"offerIsRUPerMinuteThroughputEnabled": false,
"offerMinimumThroughputParameters": {
"maxThroughputEverProvisioned": 400,
"maxConsumedStorageEverInKB": 0
}
},
"id": "xxx",
"_rid": "xxx",
"_self": "offers/xxx/",
"_etag": "\"some_etag\"",
"_ts": 123456
}
```
If the collection is serverless, there is no such offer for it because it scales automatically. Attempting to view its offer would result in an error in the output saying it's not available for a serverless database account.
=> feature: View CosmosDB collection offer

package.json
fixes: https://github.com/microsoft/vscode-cosmosdb/issues/2265
=> fix: Only show executeNoSqlQuery command on active nosql document

package.json, src/docdb/commands/executeNoSqlQuery.ts
fixes: https://github.com/microsoft/vscode-cosmosdb/issues/2265
This also makes the NoSQL query UX be identical to the Postgres query UX.
=> fix: Fix executing NoSQL query from command palette

src/getExtensionApi.ts
When upgrading the resources API, there's an error being thrown due to the versioning demanding `0.0.1`. Adding the `^` fixes that.
This pull request includes a change to the `getApiExport<T>` function in the `src/getExtensionApi.ts` file. The change updates the version parameter in the `getApi` function from a fixed version '0.0.1' to a version range '^0.0.1'. This allows the function to use any version that is compatible with version 0.0.1, rather than strictly using version 0.0.1. This change should make the function more flexible and resilient to future updates of the Azure Resource Groups extension.
=> Change API version to use ^

src/docdb/tree/DocDBAccountTreeItemBase.ts, src/docdb/tree/DocDBTreeItemBase.ts, src/docdb/utils/azureSessionHelper.ts, src/docdb/utils/rbacUtils.ts
If connecting to a database account using AAD fails because of missing RBAC permissions, we now notify the user with instructions and an option to assign a contributor role for them.
If this fails, show an error notification with a link to RBAC instructions:
"Read More" routes the user to https://aka.ms/cosmos-native-rbac
=> Add RBAC permission request flow for NoSQL accounts

src/tree/SubscriptionTreeItem.ts
Currently the extension will prefer account key auth even if local auth is disabled enforcing AAD auth from the server side.
Don't load and preserve account keys if user has opted in for AAD or if the account has local authentication disabled.
=> Improve AAD fallback if key authentication is disabled

package.json, src/AzureDBExperiences.ts, src/commands/importDocuments.ts, src/constants.ts, src/docdb/tree/DocDBDatabaseTreeItem.ts, src/docdb/tree/DocDBDatabaseTreeItemBase.ts
Fix the strings to reflect the updated Cosmos DB terminology.
* Legacy "Core (SQL)" is now "NoSQL".
* "collections" is for Mongo DB, "containers" is for NoSQL.
=> Fix Cosmos DB user facing terminology

src/webviews/theme/slickgrid.scss, src/webviews/theme/vscode-to-slickgrid2.scss
I've tried to rewrite/rethinkg slickgrid theme. 
- Changes less variables
- Suitable for dark themes
- Suitable for light themes
New theme screenshots
Old theme screenshots
=> chore: New theme for Slickgrid

src/webviews/Document/DocumentPanel.tsx, src/webviews/QueryEditor/QueryEditor.tsx, src/webviews/QueryEditor/QueryPanel/QueryPanel.tsx, src/webviews/QueryEditor/ResultPanel/ResultPanel.tsx, src/webviews/QueryEditor/ResultPanel/ResultTab.tsx, src/webviews/QueryEditor/ResultPanel/ResultTabToolbar.tsx, src/webviews/QueryEditor/ResultPanel/ResultTabViewTable.tsx, src/webviews/QueryEditor/state/QueryEditorContextProvider.tsx, src/webviews/QueryEditor/state/QueryEditorState.tsx, src/webviews/theme/vscode-to-slickgrid2.scss
This pull request includes several changes to the `QueryEditor` and `ResultPanel` components to improve the user interface and functionality. The most important changes include modifications to the styles, the addition of a new toolbar, and the removal of the `EditMode` feature.
* [`src/webviews/Document/DocumentPanel.tsx`](diffhunk://#diff-0fcab1b22e15a6415b69b5fa02920458728ab54bedeafcfbbfbc8c52563cda43L21-R22): Updated the `container` class to include a `marginTop` of `10px` and adjusted the height calculation.
* [`src/webviews/QueryEditor/QueryEditor.tsx`](diffhunk://#diff-49a3df4f62a34225e18df43ae5225278c32a02cb2de9c56a4e7b848b488bfb55R20): Added a `minWidth` of `900px` to the `root` class.
* [`src/webviews/QueryEditor/ResultPanel/ResultPanel.tsx`](diffhunk://#diff-4f2fac2e5ac3f6e48abf …
=> feat: The edit mode was removed. View | Edit | Delete buttons are available if there are selected rows

src/resolver/AppResolver.ts, src/tree/SubscriptionTreeItem.ts, src/utils/nonNull.ts
There are several scenarios where loading database resources might fail. This change adds an optional message to a commonly used nonNullValue check function and improves database resource resolution error handling. Additioally the resource ID and Name gets now masked when reporting errors to telemetry and GitHub issues.
=> Fix an issue where an internal error is not meaningful

src/panels/DocumentTab.ts, src/webviews/Document/DocumentPanel.tsx, src/webviews/Document/DocumentToolbar.tsx, src/webviews/Document/state/DocumentContextProvider.tsx, src/webviews/Document/state/DocumentState.tsx
This pull request includes significant updates to the `DocumentTab` and related components to support a new edit mode and handle document dirty state. The changes involve adding new properties and methods to manage the edit mode and dirty state, as well as updating the UI components to reflect these changes.
* [`src/panels/DocumentTab.ts`](diffhunk://#diff-26716e98f3c226c5be3af5279ed324a6963ffdca6eeba9ee210ff130ae8fdd0fL24-R25): Introduced `_mode` and `isDirty` properties, along with corresponding getter and setter for `mode`. The setter includes logic to prevent switching from 'edit' to 'view' if the document is dirty. Added new commands `setMode` and `setDirty` to handle mode changes and dirty state. [[1]](diffhunk://#diff-26716e98f3c226c5be3af5279ed324a6963ffdca6eeba9ee210ff130ae8fdd0fL …
=> feat: The use can open document for editing if document was open as read-only

src/docdb/tree/DocDBCollectionTreeItem.ts, src/docdb/tree/DocDBDatabaseTreeItemBase.ts, src/docdb/tree/DocDBDocumentTreeItem.ts, src/docdb/tree/DocDBDocumentsTreeItem.ts, src/docdb/tree/DocDBStoredProcedureTreeItem.ts, src/docdb/tree/DocDBStoredProceduresTreeItem.ts, src/docdb/tree/DocDBTriggerTreeItem.ts, src/docdb/tree/DocDBTriggersTreeItem.ts, src/graph/tree/GraphCollectionTreeItem.ts, src/graph/tree/GraphTreeItem.ts, src/mongo/tree/MongoCollectionTreeItem.ts, src/mongo/tree/MongoDatabaseTreeItem.ts, src/mongo/tree/MongoDocumentTreeItem.ts, src/postgres/tree/PostgresColumnTreeItem.ts, src/postgres/tree/PostgresDatabaseTreeItem.ts, src/postgres/tree/PostgresFunctionTreeItem.ts, src/postgres/tree/PostgresResourcesTreeItemBase.ts, src/postgres/tree/PostgresStoredProcedureTreeItem.ts, src/postgres/tree/PostgresTableTreeItem.ts
This led to the following error:
```
Error: Internal error: 'branchDataProvider.getTreeItem' threw exception Internal error: Expected value to be neither null nor undefined: parent
```
Which is now fixed:
=> Fix an issue where Mongo nodes did not have a local parent assigned

src/utils/convertors.ts
The column `id` shows up twice for some containers, because it could originally be in the `columns` (the query results), and then added again in `partitionKeyPaths`.
While this issue probably is just specific to `id` and we could also check if `id` exists in `columns` before adding to `partitionKeyPaths`, this PR ensure that we don't have any other duplicates between the 3 variables that we concatenate.
=> Prevent duplicate columns in query results table

src/mongo/tree/MongoAccountTreeItem.ts
If the connection to a Mongo RU account fails, the actual error is not shown, instead there is another error:
=> Fix an issue where a MongoDB connection error might be hidden

src/utils/vscodeUtils.ts
This is likely to happen if "id" has been removed from the cosmosDB.documentLabelFields setting.
=> Fix an issue where a Document shows as "undefined" if _id is not set

src/AzureDBExperiences.ts, src/tree/AzureDBAPIStep.ts
When creating a new database resource it currently looks like this:
This change unifies Cosmos DB naming to align better with branding and documentation:
=> Improve server names when creating a new resource

src/tree/CosmosDBAccountWizard/CosmosDBAccountCapacityStep.ts
This is based on #2386 and adds an additional "vCore" item to the capacity mode selection step when creating a new Mongo server:
* Selecting the new item opens https://learn.microsoft.com/azure/cosmos-db/mongodb/vcore/quickstart-portal in the browser and closes the wizard.
* In addition an isvCore = 'true' property is added to telemetry
=> Add vCore to Mongo Capacity Mode selection

src/webviews/MonacoEditor.tsx
Fixes #2431
This pull request includes changes to the `MonacoEditor` component in `src/webviews/MonacoEditor.tsx` to improve focus management and accessibility. The most important changes include importing a new hook, using the hook to manage focus, and updating the component's return structure to include an input element for accessibility.
Focus management improvements:
* [`src/webviews/MonacoEditor.tsx`](diffhunk://#diff-658c73b23462509bae5644a5ab3451996ec26c97b3e4231f2539e5aea0f1a60fR10): Imported the `useUncontrolledFocus` hook from `@fluentui/react-components`.
* [`src/webviews/MonacoEditor.tsx`](diffhunk://#diff-658c73b23462509bae5644a5ab3451996ec26c97b3e4231f2539e5aea0f1a60fR19): Utilized the `useUncontrolledFocus` hook within the `MonacoEditor` component to manage focus …
=> fix: Workaround to prevent Monaco loose a focus and handle "tab" key as text modifier

src/panels/BaseTab.ts, src/webviews/api/extension-server/WebviewBaseController.ts, src/webviews/index.tsx, webpack.config.ext.js, webpack.config.views.js
- Dev server is disabled for production build
- CSP rules for production build use only VSCode uri, for development build dev-server host is added
=> fix: Security improvements

src/webviews/QueryEditor/ResultPanel/ResultTabViewTree.tsx, src/webviews/mongoClusters/collectionView/components/DataViewPanelTree.tsx
- this was fixed a while ago in upstream repos, which I maintain, Slickgrid-React v5.7 (Slickgrid-Universal) via these 2 PRs 
- https://github.com/ghiscoding/slickgrid-universal/issues/1658
- https://github.com/ghiscoding/slickgrid-universal/pull/1675
- this was discussed in this upstream [Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions/1655) 
cc @tnaum-ms
Side note: I don't have any Azure DBs, so I can't really test this myself.
=> fix: remove unnecessary code since patch fix was applied in upstream repo

package.json
This setting is not used anywhere and it's not clear what it's meant to be used for.
Fixes #2398
=> Remove the obsolete showExplorer setting

src/docdb/session/QuerySession.ts, src/docdb/session/QuerySessionResult.ts, src/docdb/types/queryResult.ts, src/utils/convertors.ts, src/webviews/QueryEditor/ResultPanel/ResultPanelToolbar.tsx
Fixes #2438
- Button 'Go to next page' is disabled if hasMore is false
- No error if queryMetrics is empty
=> fix: Supports hasMore property

package.json, src/extensionVariables.ts, src/mongoClusters/MongoClustersClient.ts, src/mongoClusters/commands/addWorkspaceConnection.ts, src/mongoClusters/commands/createCollection.ts, src/mongoClusters/commands/createDatabase.ts, src/mongoClusters/commands/dropCollection.ts, src/mongoClusters/commands/dropDatabase.ts, src/mongoClusters/commands/removeWorkspaceConnection.ts, src/mongoClusters/tree/CollectionItem.ts, src/mongoClusters/tree/DatabaseItem.ts, src/utils/dialogs/getConfirmation.ts, src/utils/dialogs/showConfirmation.ts, src/webviews/mongoClusters/collectionView/CollectionView.tsx, src/webviews/mongoClusters/collectionView/collectionViewRouter.ts, src/webviews/mongoClusters/documentView/components/toolbarDocuments.tsx, src/webviews/mongoClusters/documentView/documentView.tsx, src/webviews/mongoClusters/documentView/documentsViewRouter.ts
vCore previously lacked feedback when operations were executed, such as when a document was deleted or saved.  
This PR addresses this issue.
**1. Added a new setting to enable detailed operation summaries for actions such as database drops, document additions, deletions, or similar events.**
The functionality to display operation summaries is now available in [showConfirmation.ts](https://github.com/microsoft/vscode-cosmosdb/blob/c8487ba9f3fe26eac9208216ae0d65f7621cca00/src/utils/dialogs/showConfirmation.ts).
**2. Implemented this functionality throughout the vCore extension.**
Notifications are displayed for the majority of operations:  
**3. Saving documents follows the UX approach used in the NoSQL implementation.**
The `Save` button dynamically toggles its `disabled`/`enabled` state …
=> vCore: feat: added operation summary messages

package.json, src/docdb/commands/viewDocDBCollectionOffer.ts, src/docdb/commands/viewDocDBDatabaseOffer.ts, src/docdb/registerDocDBCommands.ts
If a container has shared throughput, show the database offer instead. Add a new command to show the database offer.
=> Small throughput related improvements.

src/webviews/api/configuration/appRouter.ts, src/webviews/api/extension-server/WebviewController.ts, src/webviews/api/extension-server/trpc.ts, src/webviews/api/webview-client/vscodeLink.ts, src/webviews/mongoClusters/collectionView/CollectionView.tsx, src/webviews/mongoClusters/collectionView/components/toolbar/ToolbarMainView.tsx, src/webviews/mongoClusters/collectionView/components/toolbar/ToolbarTableNavigation.tsx, src/webviews/mongoClusters/collectionView/components/toolbar/ToolbarViewNavigation.tsx, src/webviews/mongoClusters/documentView/documentView.tsx
1. The key change in this pull request is the proper catching and wrapping of exceptions into a `TRPCError` object, which can then be correctly serialized, detected, and handled on the webview side.
2. This improved error handling has been applied throughout the MongoCluster webviews.
3. Additionally, a common function in the tRPC router has been added that displays an error message using VS Code. This new common function is now available to all webviews.
There is a follow-up work item lined up: https://github.com/microsoft/vscode-cosmosdb/issues/2521
* [`src/webviews/api/configuration/appRouter.ts`](diffhunk://#diff-d2b14fe54f82e0b1b8f400e390b6ee3a7bcaaafe6b0f67d0f371b971075dcd9fR92-R110): Added a new `displayErrorMessage` procedure to show error messages in VS Code.
* …
=> #2517 improve tRPC error handling

src/commands/attachEmulator/attachEmulator.ts, src/constants.ts, src/tree/AttachedAccountsTreeItem.ts, src/tree/attached/CosmosDBAttachedAccountsResourceItem.ts, src/tree/docdb/AccountInfo.ts, src/tree/docdb/DocumentDBAccountAttachedResourceItem.ts
This enables the Emulator support on Linux. Unfortunately I don't have a Linux setup right now, @mkrueger could you maybe help with this?
Note for investigation: this also enables it for Mongo, we should look into that as well since there is MongoDB for Linux, not sure how functional Emulator support is for that.
Addresses #2449
=> Enable Attach Emulator on Linux and MacOS

src/webviews/api/configuration/appRouter.ts
This pull request includes changes to the `src/webviews/api/configuration/appRouter.ts` file to clean up and comment out unused code related to the `demoRouter`. The most important changes include removing the `trpcToTelemetry` import and commenting out the `demoRouter` and its associated procedures.
It's left as a comment as future work around subscriptions with tRPC is planned.
=> Disabled unused tRPC showcase code (subscriptions support)

package-lock.json, src/docdb/getCosmosClient.ts, src/tree/docdb/DocumentDBAccountAttachedResourceItem.ts
Update @azure/cosmos to 4.2.0 including support for http connections and add checks to configure CosmosClient accordingly.
This allows connecting to the NoSQL emulator with `--protocol http`.
=> Add support for NoSQL Emulator without SSL/TLS

src/utils/slickgrid/mongo/toSlickGridTree.ts
Resolves https://github.com/microsoft/vscode-cosmosdb/issues/2515
This pull request includes a change to handle cases where `document._id` could be null in the `documentToSlickGridTree` function. The most important changes involve checking the `_id` field and assigning an appropriate string value based on its type.
Handling null and different types for `document._id`:
* [`src/utils/slickgrid/mongo/toSlickGridTree.ts`](diffhunk://#diff-a9c32ac0218485fcad007201423fb973ad40b11198e30c1bfbb969c62c127886R79-R92): Added logic to check if `document._id` is null, if it is of `ObjectId` type, or if it is another type, and assign the appropriate string value to `idFieldValue`.
=> fix: handle _id with a 'null' value in the mongo tree view

src/mongoClusters/tree/MongoClusterItemBase.ts, src/mongoClusters/tree/MongoClusterResourceItem.ts, src/mongoClusters/tree/workspace/MongoClusterWorkspaceItem.ts
In case of a failed connection due to incorrect auth data or inaccessible server, the action was a refresh of the entire tree resulting in long wait times and the user assuming that the operation has failed.
Changes:
1. In case of an error, the user can decide to reconnect, and only the selected cluster will be refreshed
2. The error is presented in a modal dialog so that it's easier to spot it and become aware of the authentication issue.
Improvements to error handling and user feedback:
* [`src/mongoClusters/tree/MongoClusterItemBase.ts`](diffhunk://#diff-3fe28caa41331f45255f96c2b006dd8447bade8595f061343ca18c9742314ba8R86-R94): Added a log message to the output channel when authentication fails and updated the command arguments for the error element to provide a more specific refresh …
=> fix: mongo: #2474 reconnecting with incorrect auth data

.vscode/launch.json
Update: DEBUGTELEMETRY="verbose" logs all telemetry events to the debug console which is too verbose when not currently working on telemetry. Hence set it to "true" to suppress sending and logging telemetry.
Enable verbosity only when debugging together with host extensions.
=> Always suppress telemetry when debugging 

src/panels/QueryEditorTab.ts, src/utils/survey.ts, src/webviews/QueryEditor/QueryPanel/QueryToolbarOverflow.tsx, src/webviews/QueryEditor/state/QueryEditorContextProvider.tsx, src/webviews/QueryEditor/state/QueryEditorState.tsx, src/webviews/api/configuration/appRouter.ts, src/webviews/mongoClusters/collectionView/collectionView.scss, src/webviews/mongoClusters/collectionView/components/toolbar/ToolbarMainView.tsx
Adds a "Provide Feedback" button to the NoSQL query editor if the user has been identified as a survey candidate. Usage scores will be ignored, hence the button is always visible if the user has not opted out from surveys.
The "smiley" button opens a dropdown with the option to provide feedback:
if the toolbar is collapsed, the button turns to a simple menu item without a second step.
=> Add a Feedback button to NoSQL query editor

.azure-pipelines/compliance/CredScanSuppressions.json, .config/guardian/.gdnsuppress
This PR should stop our CredScan build issues on our internal build pipeline.
---
This pull request includes updates to the compliance and security suppression files to handle new test files and update metadata. The most important changes include adding new entries to the `CredScanSuppressions.json` file and updating the `.gdnsuppress` file with new signatures and dates.
Updates to compliance suppressions:
* [`.azure-pipelines/compliance/CredScanSuppressions.json`](diffhunk://#diff-74a247523e634ec016aa955beb1fe16a03af28b92aa88de930823de56b62766eR19-R30): Added suppressions for fake credentials used in unit tests for `cosmosDBConnectionStrings.test.ts` and `mongoConnectionStrings.test.ts`.
Updates to security suppressions:
* [`.config/guardian/.gdnsuppress`](diffhunk://#diff-4879d5f3a0b7cfb …
=> Updated CredScan Configuration

l10n/bundle.l10n.json, src/webviews/cosmosdb/QueryEditor/QueryPanel/QueryToolbarOverflow.tsx
This pull request makes a small but meaningful change to improve accessibility in the `RunQueryButton` component. Specifically, it adds an `aria-label` to the `menuButton` to provide a more descriptive label for screen readers.
* [`src/webviews/cosmosdb/QueryEditor/QueryPanel/QueryToolbarOverflow.tsx`](diffhunk://#diff-b1f4c6160d06097fa41d9e2563c8650bec9c7f6610309f984aa82e1c8b49e5b9L90-R93): Updated the `menuButton` props in the `RunQueryButton` component to include an `aria-label` with the text "Show history of previous queries" for better accessibility.
=> Fix issue #2660: Resolve l10n issue in QueryPanel run button menu.

l10n/bundle.l10n.json, src/webviews/cosmosdb/QueryEditor/QueryPanel/QueryToolbarOverflow.tsx
This pull request includes a minor change to the `DuplicateTabButton` component in the `QueryToolbarOverflow` file. The `aria-label` for the button was updated to improve clarity and consistency.
* [`src/webviews/cosmosdb/QueryEditor/QueryPanel/QueryToolbarOverflow.tsx`](diffhunk://#diff-b1f4c6160d06097fa41d9e2563c8650bec9c7f6610309f984aa82e1c8b49e5b9L195-R195): Updated the `aria-label` of the `DuplicateTabButton` from `'Copy into new tab'` to `'Duplicate'`.
=> Fix issue #2661: Resolve l10n issue in QueryPanel

l10n/bundle.l10n.json, src/webviews/cosmosdb/QueryEditor/ResultPanel/ResultTabToolbar.tsx
This pull request includes a minor change to the `ResultTabToolbar` component in the `ResultPanel` of the CosmosDB Query Editor. The `aria-label` attribute was removed from the `Toolbar` component fixing the not needed double announcement. Just the button text should be read.
* [`src/webviews/cosmosdb/QueryEditor/ResultPanel/ResultTabToolbar.tsx`](diffhunk://#diff-5cdf9f37b21ee76f767b33bc6d49af1c805250506c1d46eedb89dea7e5ea64bbL54-R54): Removed the `aria-label` attribute (`l10n.t('Result view toolbar')`) from the `Toolbar` component.
=> Fix issue #2668: Corrected screen reader button announcement in ResultTabToolbar

l10n/bundle.l10n.json, src/webviews/cosmosdb/QueryEditor/ResultPanel/IndexMetricsView.tsx, src/webviews/cosmosdb/QueryEditor/ResultPanel/StatsTab.tsx
This pull request adds more descriptive text for "Learn more" links and updating the localization file to support these changes.
* [`l10n/bundle.l10n.json`](diffhunk://#diff-829b512e02461234524c007941f3260e67a43b109f48bedf257ab8e8033cc527R350-R351): Added new localized strings for "Learn more about index metrics…" and "Learn more about query metrics…" to provide more descriptive context for links.
* [`src/webviews/cosmosdb/QueryEditor/ResultPanel/IndexMetricsView.tsx`](diffhunk://#diff-5b0779b73027ea1cf9f5fff462b9b46d635305f2981fa81eacad0a46f651a9fcL44-R47): Updated the "Learn more" link for index metrics to include an `aria-label` with a more descriptive message, improving accessibility.
* [`src/webviews/cosmosdb/QueryEditor/ResultPanel/StatsTab.tsx`](diffhunk://#diff-4b01f3f72965fa3a085d …
=> Fix issue #2663: Improve arial labels for "Learn more…" links.

src/webviews/cosmosdb/QueryEditor/ResultPanel/IndexMetricsView.tsx, src/webviews/cosmosdb/QueryEditor/ResultPanel/StatsTab.tsx
This pull request improves accessibility in the CosmosDB Query Editor by adding ARIA labels and keyboard navigation support to table rows in the `IndexMetricsView` and `StatsTab` components.
* **`IndexMetricsView` component (`src/webviews/cosmosdb/QueryEditor/ResultPanel/IndexMetricsView.tsx`)**:
- Added `aria-label` attributes to table rows, combining section titles and index values for better screen reader support.
- Enabled keyboard navigation by adding `tabIndex={0}` to table rows.
* **`StatsTab` component (`src/webviews/cosmosdb/QueryEditor/ResultPanel/StatsTab.tsx`)**:
- Added `aria-label` attributes to table rows, combining tooltip text and formatted metric values for accessibility.
- Enabled keyboard navigation by adding `tabIndex={0}` to table rows.
Fixes #2669
=> Fixed aria labels in query editor stats & result tab.

src/commands/createContainer/CosmosDBPartitionKeyStep.ts, src/commands/createContainer/createContainer.ts
Fixed: #2703
- Replace enum with string literals for hierarchy steps in CosmosDBPartitionKeyStep
- Add id for step to avoid value caching
=> chore: Cleaning value in Container PK step for second and third step

src/webviews/cosmosdb/QueryEditor/QueryPanel/RunQueryButton.tsx
Fixes #2675
This pull request updates the `RunQueryButton` component in the CosmosDB Query Editor to improve menu behavior and code clarity. The most significant changes involve replacing `MenuItemCheckbox` with `MenuItemRadio` for better semantics, adding a key to the `Menu` component for React rendering optimization, and enhancing state management for throughput bucket selection.
* Replaced `MenuItemCheckbox` with `MenuItemRadio` to ensure correct behavior for mutually exclusive menu options. (`src/webviews/cosmosdb/QueryEditor/QueryPanel/RunQueryButton.tsx`, [[1]](diffhunk://#diff-f6409d4acd7793ae0efb7e29b1384081157d98c5ec77d2c673943d4b73baf374L11-R11) [[2]](diffhunk://#diff-f6409d4acd7793ae0efb7e29b1384081157d98c5ec77d2c673943d4b73baf374R125-R163)
* Added `hasSubmenu` to the …
=> Fixed throughput buckets submenu.
