package.json
src/extension.ts
src/mongo/mongo.ts

In the continued effort of moving from mongo to cosmosdb, this refactoring focuses just on updating package.json

Update package.json to use Cosmos DB instead of Mongo

---

src/mongo/mongo.ts

We only want to filter based on subscription. Also change the label when no resources are found. It's weird to say 'Add a _filter_' to see more resources
#23

Ignore resource group filters

---

package.json
src/extension.ts

command to launch mongo shell

---

package.json
src/azure-account.api.d.ts
src/extension.ts
src/nodes.ts

moved to the external azure-account extension and moved to using keytar node module.

move to external azure-account api

---

package.json
src/extension.ts
src/telemetry.ts

Add basic telemetry for commands

---

README.md

I also added a section about telemetry, since that was recently added (mostly copied from vscode-docker repo)

Refactor README from Mongo to Cosmos DB

---

src/nodes.ts

Small clean up on the account extension's side.

Update command id

---

thirdpartynotices.txt

Adds license notice for all third party modules used within this
extension.

Update third party licenses.

---

src/extension.ts

Fix command arguments getting passed as array

---

src/extension.ts

[Use this instead](https://github.com/Microsoft/vscode-azureappservice/pull/47/commits/514ff9cb2614d9f8c009910e409f851026119ad0) for fixing [Issue 1](https://github.com/Microsoft/vscode-cosmosdb/issues/1).

Create an untitled file on new scrapbook

---

src/mongo/commands.ts

Collection click - handle when no workspace selected

---

package.json
src/mongo/nodes.ts

Redoing [PR#66](https://github.com/Microsoft/vscode-cosmosdb/pull/66) - mixed up some commits there due to a rebase. 
package.json : expose max docs as global setting; 
nodes.ts: import that setting when using maxdocs

Allow user to change page limit

---

.vscode/settings.json

Similar to [PR81](https://github.com/Microsoft/vscode-azureappservice/pull/81) of App Service.

Code formatting : Settings to make them consistent and automatic.

---

src/commands.ts
src/extension.ts

Add ignoreFocusOut to fix #67

---

package.json
src/commands.ts
src/docdb/nodes.ts
src/extension.ts
src/nodes.ts

Implement drop DB and Drop Collection 

---

package.json
src/commands.ts
src/docdb/nodes.ts
src/extension.ts

Fixes #83 
Also: 
Consolidate the update commands to cause less confusion
Remove OpenCollection - the UI wouldn't make sense.

Persist documents to Azure, create&delete documents

---

package.json
src/constants.ts
src/docdb/commands.ts
src/extension.ts
src/mongo/commands.ts
src/mongo/nodes.ts

Bringing Mongo's implementation to parity with DocDB currently in master.

Mongo : Create and Delete collections and documents

---

src/commands.ts
src/docdb/commands.ts
src/extension.ts
src/nodes.ts

Seems like a more correct name.

Rename CosmosDBResourceNode -> CosmosDBAccountNode

---

package-lock.json
package.json
src/DocumentEditor.ts
src/constants.ts
src/docdb/commands.ts
src/docdb/nodes.ts
src/extension.ts
src/mongo/commands.ts
src/mongo/nodes.ts
src/nodes.ts
src/util.ts
thirdpartynotices.txt

1. Always open cosmos-document.json in an extension-specific directory
1. Dirty dot on file should match dirty state in Azure
1. Remove some unused code
Fixes #109 
Fixes #118

Tie 'Save' action to 'Update to Azure' action

---

src/DocumentEditor.ts
src/extension.ts

In addition to commands
Fixes #125

Use our telemetry/error handling for vscode events

---

src/extension.ts
src/mongo/commands.ts
src/util.ts

Open new result file for each command executed

---

src/mongo/nodes.ts

Fix mongo createCollection

---

src/docdb/commands.ts
src/docdb/nodes.ts
src/mongo/commands.ts
src/mongo/nodes.ts

These documents aren't in order, but I think it makes sense to be at the top since it's a new document. The next time the user does a hard refresh, it will show up in order.
Fixes #123

Add new documents to the explorer

---

.gitignore
package-lock.json

Change versioning in package-lock

---

src/docdb/commands.ts
src/mongo/commands.ts

DocDB createdocument : disallow empty docID

---

resources/graphClient/graphClient.css
resources/graphClient/graphClient.html
src/graph/GraphViewServer.ts

Improve error display

---

src/DocumentEditor.ts
src/mongo/nodes.ts
src/nodes.ts

Fixes #146 .
The error cases get bubbled up from the scenarios I tested

Show output message on success

---

src/docdb/commands.ts
src/docdb/nodes.ts
src/mongo/commands.ts
src/mongo/nodes.ts

After deleting a node successfully, remove the node from the cache.

---

CHANGELOG.md
README.md

- Update features to reflect our changes in plan
- Update telemetry notice to use generic text with link to privacy statement (as recommended)

Prep for 0.2.0 release

---

src/graph/GraphViewServer.ts

Work around jbmusso/gremlin-javascript#93.

Work around gremlin client bug affecting UTF-8 data

---

resources/graphClient/graphClient.css
resources/graphClient/graphClient.html

Styling changes (last ones from Chet), plus always show Graph/JSON tabs

---

src/docdb/commands.ts

Fix graph vs. doc collection creation

---

resources/graphClient/graphClient.html

Run execute on enter

---

src/graph/client/graphClient.ts

outV refers to the source of the edge (the "tail"), inV refers to the target of the edge (the "head").

Correct direction of arrows Fixes #196

---

package-lock.json
resources/graphClient/graphClient.css
resources/graphClient/graphClient.html
src/graph/GraphViewsManager.ts
src/graph/client/graphClient.ts

The hardcoded pixel numbers are to account for the static headers

Height resizes responsively

---

src/graph/client/graphClient.ts

Separate graphics a little bit better, still in same file for now.

Minor refactoring: GraphView

---

resources/graphClient/graphClient.css

Fix icon margin

---

package.json
src/DocumentEditor.ts
src/extension.ts
src/mongo/commands.ts
src/mongo/nodes.ts

- Fix 'File not found' error. (fix #226)
- Inform user about (addressing #246)

Cleaner VSCode re-opening (no temp file errors)

---

src/mongo/nodes.ts

fix findDocByID

---

src/mongo/commands.ts

- create an adhoc MongoCollectionNode for the update operation.
- Fix #257

Fix findOne regression bug

---

resources/graphClient/graphClient.css
resources/graphClient/graphClient.html
src/graph/client/graphClient.ts

There will still be some adjustments after meeting with UX, but this handles the major changes.

Pick up VS Code theme, fixes #228

---

src/mongo/tree/MongoCollectionTreeItem.ts

Add mongo.collection.count functionality to scrapbook

---

src/mongo/tree/MongoAccountTreeItem.ts

This was requested by Chris a while ago
Fixes #71

Don't display admin database

---

src/CosmosEditorManager.ts
src/constants.ts
src/docdb/tree/DocDBCollectionTreeItemBase.ts
src/docdb/tree/DocDBDatabaseTreeItemBase.ts
src/docdb/tree/DocDBDocumentTreeItem.ts
src/graph/tree/GraphCollectionTreeItem.ts
src/mongo/tree/MongoCollectionTreeItem.ts
src/mongo/tree/MongoDatabaseTreeItem.ts
src/mongo/tree/MongoDocumentTreeItem.ts

Use 'cancel' instead of 'close'

---

src/mongo/tree/MongoDocumentTreeItem.ts

Document Update : throw error if doc ID is not found.

---

src/docdb/tree/DocDBTreeItemBase.ts
src/mongo/tree/MongoCollectionTreeItem.ts

Double batchSize on click, and re-init on 'clearCache'

---

src/docdb/tree/DocDBAccountTreeItemBase.ts
src/docdb/tree/DocDBDatabaseTreeItemBase.ts
src/mongo/tree/MongoAccountTreeItem.ts
src/mongo/tree/MongoDatabaseTreeItem.ts

Name validation - DocDB DB+Collections, Mongo collections

---

package.json

Add create account to subscription item context menu. 

---

src/docdb/tree/DocDBDocumentTreeItem.ts
src/mongo/tree/MongoDocumentTreeItem.ts

Updating empty documents

---

package.json
src/docdb/tree/DocDBDocumentTreeItem.ts
src/mongo/tree/MongoDocumentTreeItem.ts

Fixes #263 
Fixes #256 
Individual PR's have been approved.

Bug fixes 263 and 256

---

src/mongo/tree/MongoCollectionTreeItem.ts

Fix typo. Docuemnt -> Document

---

src/graph/registerGraphCommands.ts

Must've been a copy/paste error

Fix graph delete commands

---

src/docdb/tree/DocDBAccountTreeItemBase.ts
src/graph/GraphConfiguration.ts
src/graph/GraphViewServer.ts
src/graph/GraphViewsManager.ts
src/graph/gremlinEndpoints.ts
src/graph/tree/GraphAccountTreeItem.ts
src/graph/tree/GraphCollectionTreeItem.ts
src/graph/tree/GraphDatabaseTreeItem.ts
src/tree/AttachedAccountsTreeItem.ts
src/tree/CosmosDBAccountProvider.ts

Fix gremlin endpoint change and error handling, fixes #322

---

src/mongo/tree/MongoDocumentTreeItem.ts

Fix mongo doc update/delete error checking

---

package.json
src/commands.ts
src/commands/createCosmosDBAccount.ts
src/commands/deleteCosmosDBAccount.ts
src/docdb/tree/DocDBAccountTreeItemBase.ts
src/extension.ts
src/mongo/tree/MongoAccountTreeItem.ts
src/table/tree/TableAccountTreeItem.ts
src/tree/CosmosDBAccountProvider.ts
src/utils/azureUtils.ts

Delete CosmosDB accounts from the extension

---

src/mongo/editors/MongoFindResultEditor.ts
src/mongo/tree/MongoCollectionTreeItem.ts

Fix query filters in find() with a JSON parse

---

src/mongo/tree/MongoCollectionTreeItem.ts

Add findOne to MongoCollectionTreeItem's executeCommand

---

src/tree/AttachedAccountsTreeItem.ts
src/utils/vscodeUtils.ts

keytar require - remove assumption on node_module disk layout

---

package.json

Update to latest vscode dependencies fixes #390

---

src/tree/AttachedAccountsTreeItem.ts
src/tree/CosmosDBAccountProvider.ts

Add type of account to account label

---

.travis.yml
package.json
tslint.json

Add tslint (with some disabled rules)

---

src/graph/client/graphClient.ts
src/graph/client/graphTypes.ts
src/mongo/MongoCommand.ts
src/mongo/services/schemaService.ts
src/mongo/tree/MongoCollectionTreeItem.ts
tslint.json

#316 
Some of these rules I'm going to grandfather in because they're no value and some of this code is not well understood by us yet and I'd rather not be messing with it.

Delinting step 1

---

package.json
src/commands/deleteCosmosDBAccount.ts
src/tree/CosmosDBAccountProvider.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountNameStep.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountStep.ts

See this PR for more info: https://github.com/Microsoft/vscode-azuretools/pull/127
Dependent on this PR, which has not been merged yet: https://github.com/Microsoft/vscode-azuretools/pull/132

Update ui package to leverage new subscription api on nodes

---

src/CosmosEditorManager.ts

Re-opening VSCode multiple times now shouldn't break update document

---

CHANGELOG.md
package.json

Cherry picked the 'prep for release' commits in rel/0.5.1 to master. 
The other commits have already been cherry picked: 
[Regression fix](https://github.com/Microsoft/vscode-cosmosdb/commit/095352f0c894f86a0f33470dd1cf963807ce490e)
[Add pre-GA graphs issue to readme](https://github.com/Microsoft/vscode-cosmosdb/commit/095352f0c894f86a0f33470dd1cf963807ce490e)
[Add upload-vsix to TravisCI](https://github.com/Microsoft/vscode-cosmosdb/commit/e0d41f175b175de609f019c7c291e7512cd90892)

Update changelog and package.json in master to 0.5.1

---

package.json
src/docdb/registerDocDBCommands.ts
src/docdb/tree/DocDBCollectionTreeItem.ts
src/docdb/tree/DocDBStoredProcedureTreeItem.ts
src/docdb/tree/DocDBStoredProceduresTreeItem.ts

Delete stored procedures 

---

src/mongo/registerMongoCommands.ts

Persist connected Mongo DB

---

package.json
src/docdb/registerDocDBCommands.ts
src/docdb/tree/DocDBCollectionTreeItem.ts
src/docdb/tree/DocDBDocumentsTreeItem.ts

Disable displaying stored procs until view/edit implemented

---

src/tree/AttachedAccountsTreeItem.ts

Add DB to id for multi-tenant scenario, fixes #482

---

src/mongo/tree/MongoCollectionTreeItem.ts

Defer to mongo shell for unsupported cases of multiple parameter calls.

---

grammar/JavaScript.tmLanguage.json
grammar/Regular Expressions (JavaScript).tmLanguage
package.json

Not positive this is doing everything right, but it stops interfering with JavaScript, and intellisense and highlighting still work (and I added CTI testcases).

Stop publishing JS grammar, fixes #464

---

package.json
src/extensionVariables.ts
src/mongo/registerMongoCommands.ts
src/mongo/tree/MongoAccountTreeItem.ts
src/mongo/tree/MongoDatabaseTreeItem.ts

Fixes #487 
Fixes #481 
Requires this PR: https://github.com/Microsoft/vscode-azuretools/pull/148

Fix '(Connected)' label bugs

---

package.json
src/tree/CosmosDBAccountProvider.ts

And hide stored procedure command since we're not shipping them yet
Fixes #495

Fix creating account in command palette

---

src/mongo/grammar/visitors.ts

use correct error column, fixes #500

---

src/mongo/tree/MongoCollectionTreeItem.ts

findOne : no args

---

.travis.yml

Didn't find anything better that was easy to do.
fixes #408

Show build errors on travis

---

src/mongo/shell.ts
src/tree/AttachedAccountsTreeItem.ts
src/utils/vscodeUtils.ts
tslint.json

- no unused expressions 
- max-classes-per-file
- no-empty (no empty blocks of code)

Implement few tslint rules

---

src/mongo/tree/MongoCollectionTreeItem.ts

Don't throw exception on dropping non-existent collection, fixes #510

---

src/experiences.ts

Agreed to in #520 but got left out.

Add (DocumentDB) to SQL description

---

package.json
src/tree/CosmosDBAccountProvider.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountApiStep.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountCreateStep.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountNameStep.ts

This was mainly to split steps into discrete 'Prompt' and 'Execute' steps

Refactor wizard to work with latest ui package

---

src/CosmosEditorManager.ts
src/commands/deleteCosmosDBAccount.ts
src/constants.ts
src/docdb/tree/DocDBCollectionTreeItem.ts
src/docdb/tree/DocDBDatabaseTreeItemBase.ts
src/docdb/tree/DocDBDocumentTreeItem.ts
src/docdb/tree/DocDBStoredProcedureTreeItem.ts
src/graph/tree/GraphCollectionTreeItem.ts
src/mongo/tree/MongoCollectionTreeItem.ts
src/mongo/tree/MongoDatabaseTreeItem.ts
src/mongo/tree/MongoDocumentTreeItem.ts

1. Make confirmation messages modal (https://github.com/Microsoft/vscode-azuretools/issues/151)
1. Use 'Delete' instead of 'Yes' when asking to delete something
1. Leverage common DialogResponses class

Improve warning messages

---

package.json
src/docdb/registerDocDBCommands.ts

Change category of 'create Stored Procedure'

Fix absence of 'delete Stored Procedure'. Fixes #579

---

src/mongo/tree/MongoAccountTreeItem.ts

Better error message for missing connection string

---

package.json
src/constants.ts
src/docdb/tree/DocDBDocumentTreeItem.ts

Pass partitionKey values appropriate to type of collection and document

---

CHANGELOG.md

There are still known scenarios for this issue, so remove comment saying it was completely fixed for now.

Remove misleading bug fix comment

---

src/docdb/tree/DocDBCollectionTreeItem.ts
src/experiences.ts
src/mongo/languageServer.ts
tslint.json

I find this rule useful. Don't know what others think of it's efficacy.

implement no-consecutive-blank-lines in the repo

---

src/CosmosEditorManager.ts
src/docdb/tree/DocDBDatabaseTreeItemBase.ts
src/extension.ts
src/graph/GraphViewServer.ts
src/graph/GraphViewsManager.ts
src/graph/client/graphClient.ts
src/graph/client/graphTypes.ts
src/graph/tree/GraphCollectionTreeItem.ts
src/mongo/MongoCommand.ts
src/mongo/MongoScrapbook.ts
src/mongo/languageServer.ts
src/mongo/services/MongoCodeLensProvider.ts
src/mongo/services/completionItemProvider.ts
src/mongo/services/languageService.ts
src/mongo/services/mongoScript.ts
src/mongo/services/schemaService.ts
src/mongo/shell.ts
src/mongo/tree/MongoAccountTreeItem.ts
src/mongo/tree/MongoCollectionTreeItem.ts
src/mongo/tree/MongoDatabaseTreeItem.ts
src/tree/AttachedAccountsTreeItem.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountNameStep.ts
src/tree/CosmosDBAccountWizard/ICosmosDBWizardContext.ts
src/utils/vscodeUtils.ts
tslint.json

Ensures properties/expressions are separated by semicolon.

Implement tslint rule 'semicolon' -

---

CHANGELOG.md
src/tree/CosmosDBAccountProvider.ts

Since I was already making this fix, I went ahead and cleaned up the changelog a little bit, too.

Fix spacing of api label

---

src/graph/GraphViewServer.ts
src/graph/client/graphClient.ts
tslint.json

One exception, explained in code comments.

Implement prefer-for-of in the repo

---

package.json
thirdpartynotices.txt

Following [this commit](https://github.com/Microsoft/vscode-azurearmtools/pull/113/commits/a8647953cb7b5b3a3f4c0c41c29f51fa6db76aa5)

Add a lint command to perform fixes

---

src/CosmosEditorManager.ts
src/commands/deleteCosmosDBAccount.ts
src/mongo/tree/MongoCollectionTreeItem.ts
src/tree/CosmosDBAccountProvider.ts
thirdpartynotices.txt

 Filter out invalid accounts under a subscription

---

src/mongo/tree/MongoCollectionTreeItem.ts

find operation: Use EJSON to parse query and projection

---

.gitignore
.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
package.json

Enables parse tree in output window and creating graphs via edit context menu

Enable debugging Mongo grammar via mike-lischke.vscode-antlr4 extension

---

CHANGELOG.md
package.json
src/mongo/tree/MongoCollectionTreeItem.ts
src/mongo/tree/MongoDocumentTreeItem.ts
src/tree/AttachedAccountsTreeItem.ts
test/attachedAccountsTreeItem.test.ts

- Cherry pick commits
- Add to CHANGELOG
- Version bump.

Cherry pick + Prep for 0.7.2

---

src/mongo/MongoScrapbook.ts
src/mongo/registerMongoCommands.ts
src/mongo/services/MongoCodeLensProvider.ts
test/mongoGetCommand.test.ts

Fixes #609, #659 
Also adds telemetry for provideCodeLenses (failures only).

Cannot read property text of undefined

---

README.md

Fix scrapbooks link

---

.vscode/extensions.json
README.md
src/tree/AttachedAccountsTreeItem.ts

Fixes #698 
Related: #662, #692, #675, #669

Only default to local port for Mongo connection if it's running

---

src/mongo/MongoScrapbook.ts
src/mongo/errorListeners.ts
test/mongoGetCommand.test.ts

Use actual error message from lexer

---

package.json
src/CosmosEditorManager.ts
src/commands/deleteCosmosDBAccount.ts
src/docdb/registerDocDBCommands.ts
src/extension.ts
src/extensionVariables.ts
src/graph/GraphViewServer.ts
src/graph/registerGraphCommands.ts
src/mongo/MongoScrapbook.ts
src/mongo/registerMongoCommands.ts
src/mongo/services/MongoCodeLensProvider.ts
src/mongo/tree/MongoCollectionTreeItem.ts
src/tree/CosmosDBAccountProvider.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountApiStep.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountCreateStep.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountNameStep.ts
src/utils/telemetry.ts
src/utils/vscodeUtils.ts

I took care of all the breaking changes related to the last update in the UI package, but I'll let Stephen or Prashanth take care of the user agent stuff that was also included in that update

Preregister extension variables for ui package

---

src/mongo/tree/MongoCollectionTreeItem.ts

Pending @fiveisprime 's thoughts on the UX of this.

Fix #614 Reject promise on catching error.

---

src/graph/tree/GraphTreeItem.ts

Use collection.id instead of label when creating GraphConfig`

---

src/docdb/registerDocDBCommands.ts
src/docdb/tree/DocDBAccountTreeItem.ts
src/graph/tree/GraphAccountTreeItem.ts

- Change contextValue in registerCommands.createStoredProc
- Add StoredProcsTreeItem to isAncestorOf for DocDB&Graph AccountTreeItems
Fixes #718

enable createStoredProc from command palette

---

src/docdb/tree/DocDBStoredProceduresTreeItem.ts

create stored procedure: Add validation for input

---

src/CosmosEditorManager.ts
src/docdb/tree/DocDBStoredProceduresTreeItem.ts

Replace contents of cosmos-result.json with blank text after opening.

---

src/mongo/MongoScrapbook.ts

executeCommands: catch and rethrow error with relevant command.

---

package.json

See Microsoft/vscode-languageserver-node#378

 Fix issue with vscode-languageclient 4.4.0

---

src/graph/registerGraphCommands.ts
src/graph/tree/GraphAccountTreeItem.ts
src/graph/tree/GraphCollectionTreeItem.ts

showExplorer on cmd palette: Resolve collectionTreeItem to GraphTreeItem

---

package.json
src/extension.ts

Need this for Connections node in App Service

Added get database command.

---

package.json

Add gremlin to graph category

---

package.json

Brings up the Azure panel with ctrl/cmd+shift+a

Add shortcut key for Azure View

---

package.json
src/tree/AttachedAccountsTreeItem.ts

Modify context value, add glob pattern to attachDatabaseAccounts node.

---

package.json

Possible fix for issue #857

---

package.json
src/extension.ts
src/mongo/mongoConnectionStrings.ts
src/mongo/tree/MongoDatabaseTreeItem.ts
test/mongoConnectionStrings.test.ts

Model of command that returns the connection string

Added api.getConnectionString command

---

src/mongo/tree/MongoCollectionTreeItem.ts

Remove second EJSON parsing of query arguments.

---

src/docdb/tree/DocDBAccountTreeItemBase.ts
src/mongo/tree/MongoAccountTreeItem.ts
src/utils/timeout.ts

Inform user to start emulator on timeout(SQL) or specific error(Mongo)

---

src/docdb/registerDocDBCommands.ts
src/mongo/registerMongoCommands.ts
src/mongo/tree/MongoAccountTreeItem.ts
src/mongo/tree/MongoDatabaseTreeItem.ts

Reveal document, collection, db nodes after creation

---

src/commands/api/getConnectionString.ts
src/docdb/tree/DocDBDatabaseTreeItemBase.ts

Add supporting of doc db SQL databases.

---

README.md

Remove "We've Moved"

---

src/commands/api/DatabaseAccountTreeItemInternal.ts
src/commands/api/DatabaseTreeItemInternal.ts
src/commands/api/apiCache.ts
src/commands/api/findTreeItem.ts
src/vscode-cosmosdb.api.d.ts

~~Currently based on this PR: https://github.com/Microsoft/vscode-cosmosdb/pull/942~~

Add support for account-level connection strings

---

src/ParsedConnectionString.ts
src/commands/api/DatabaseAccountTreeItemInternal.ts
src/commands/api/DatabaseTreeItemInternal.ts
src/commands/api/apiCache.ts
src/commands/api/findTreeItem.ts
src/commands/api/pickTreeItem.ts
src/docdb/docDBConnectionStrings.ts
src/docdb/tree/DocDBDatabaseTreeItemBase.ts
src/mongo/mongoConnectionStrings.ts
src/tree/AttachedAccountsTreeItem.ts
src/vscode-cosmosdb.api.d.ts
test/docDBConnectionStrings.test.ts

Used by the App Service extension for the connections feature

Support DocDB resources in extension api

---

src/constants.ts
src/docdb/registerDocDBCommands.ts
src/docdb/tree/DocDBTreeItemBase.ts
src/extension.ts
src/graph/registerGraphCommands.ts
src/mongo/tree/MongoCollectionTreeItem.ts

Fixes #681
I initially chose 500ms, but it seemed too long a time to debounce. I chose 200ms as it looked improbable a user could try opening 2 documents within that time frame.

Add debounce to openDocument, openGraph, openStoredProc

---

src/mongo/MongoScrapbook.ts

Object to context : add error to problems instead of throwing.

---

webpack.config.js

Fixes #1012 
Exclude clipboardy from webpack.

Fix clipboard copy

---

src/docdb/tree/DocDBAccountTreeItemBase.ts
src/mongo/tree/MongoAccountTreeItem.ts

Will help in situations like https://github.com/Microsoft/vscode-cosmosdb/issues/1013.

Improve emulator connection messages

---

.vscode/launch.json
.vscodeignore
package-lock.json

Fixes #1011 
Need grammar folder to end up in package

Fix scrapbook highlighting

---

.vscode/launch.json
src/experiences.ts
src/tree/AttachedAccountsTreeItem.ts
src/tree/CosmosDBAccountProvider.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountCreateStep.ts

Stop relying on tag to distinguish between APIs

---

package-lock.json
package.json

Fixes #1020 
Depends on https://github.com/Microsoft/vscode-azuretools/pull/397

Fix opening graph

---

package-lock.json
package.json
webpack.config.js

Fix Linux opn and clipboard copy

---

.vscode/extensions.json
.vscode/settings.json

Update tslint extension

---

package-lock.json
package.json
src/tree/CosmosDBAccountProvider.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountApiStep.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountCreateStep.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountNameStep.ts

Based on this PR: https://github.com/Microsoft/vscode-azuretools/pull/444

Use updated wizard with back button

---

src/graph/GraphViewServer.ts

Replace sole use of new Buffer(str) with Buffer.from(str)

---

resources/graphClient/graphClient.html
src/graph/GraphViewServerSocket.ts
src/graph/GraphViewsManager.ts
src/graph/client/graphClient.ts
src/graph/registerGraphCommands.ts

- Create a panel on a request for graph explorer
- Due [restrictions on accessing local content](https://code.visualstudio.com/api/extension-guides/webview#loading-local-content), I've converted file locations into absolute paths under the vscode-resource sheme. 
- Fixes #931

previewHtml -> webview

---

package-lock.json
package.json
src/extension.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountCreateStep.ts

See release: https://github.com/Microsoft/vscode-azuretools/releases/tag/v0.23.0-ui

Bump ui package to 0.23.0

---

package.json

[Post-Build] Add friendly language name

---

.vscode/launch.json
src/mongo/shell.ts

[Post-Build] Make end of result sentinel less ambiguous

---

package.json

fix https://github.com/microsoft/vscode-cosmosdb/issues/837

remove Update to Cloud from command palette

---

package-lock.json
package.json
src/extensionVariables.ts
src/mongo/languageClient.ts
webpack.config.js

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1151 (See https://github.com/microsoft/vscode-azuretools/pull/550 for more info)
Breaking change in dev package means this extension has to instantiate it's own `StringReplacePlugin` in webpack config

Fix shared icons

---

src/CosmosEditorManager.ts

Change prompt message in onDidSaveTextDocument

---

CHANGELOG.md
package-lock.json
package.json

The changelog doesn't yet refer to #1178.

Prep for release 0.10.3

---

CHANGELOG.md
package-lock.json
package.json

0.10.3 -> 0.11.0

---

package-lock.json
package.json
src/CosmosEditorManager.ts
src/commands/importDocuments.ts
src/extension.ts
src/extensionVariables.ts
src/mongo/MongoScrapbook.ts
src/mongo/tree/MongoCollectionTreeItem.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountCreateStep.ts
src/tree/SubscriptionTreeItem.ts

There are a lot of spots where there are forEach output loops.  I didn't use appendLog there but tried to make sure I did right before things were listed.  Here's an example of how it looks:

Update OutputChannel and LocationStep

---

src/mongo/tree/MongoDatabaseTreeItem.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1218
I thought that this might be a regression from updating the Mongodb package, but that doesn't seem to be the case.

Throw userError rather than return undefined

---

src/commands/importDocuments.ts
src/utils/vscodeUtils.ts
src/utils/workspacUtils.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1173

Get rid of 📁 workspace.rootPath 🌲

---

package.json
src/commands/api/DatabaseAccountTreeItemInternal.ts
src/experiences.ts
src/tree/AttachedAccountsTreeItem.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountCreateStep.ts
src/tree/SubscriptionTreeItem.ts
test/nightly/azureResourceMongoDB.test.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1237

🆙📅 Update API names 📛

---

src/extension.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1275

Add collapseAll 🙏 to treeView 🌲👀

---

src/commands/importDocuments.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1266

Make the uri.fsPath lowercase to handle .JSON, .Json, etc

---

package.json

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1291
Added `...` to make it more standard with other extensions

Add ... to appropriate command titles

---

src/mongo/MongoScrapbook.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/605

Remove excess logging

---

src/commands/api/pickTreeItem.ts
src/docdb/tree/DocDBAccountTreeItemBase.ts
src/docdb/tree/DocDBDocumentTreeItem.ts
src/extension.ts
src/graph/GraphViewServer.ts
src/graph/GraphViewServerSocket.ts
src/graph/GraphViewsManager.ts
src/graph/client/graphClient.ts
src/mongo/MongoScrapbook.ts
src/mongo/MongoShell.ts
src/mongo/languageClient.ts
src/mongo/registerMongoCommands.ts
src/mongo/services/MongoCodeLensProvider.ts
src/mongo/services/languageService.ts
src/mongo/services/schemaService.ts
src/mongo/setConnectedNode.ts
src/mongo/tree/MongoDatabaseTreeItem.ts
src/mongo/tree/MongoDocumentTreeItem.ts
src/tree/AttachedAccountsTreeItem.ts
src/utils/timeout.ts
tslint.json

`variable-declaration` had the most problems, so I left that for another day.

Turn on typedef lint rule

---

CHANGELOG.md
package-lock.json
package.json
src/mongo/languageClient.ts

Just porting PR https://github.com/microsoft/vscode-cosmosdb/pull/1356 over to master

Fix error "Language client is not ready yet"

---

.azure-pipelines/common/build.yml
package-lock.json
package.json

10 is the version used in VS Code v1.31 (the minimum engine version)

Make Node version consistent

---

src/tree/CosmosDBAccountWizard/CosmosDBAccountApiStep.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/927

Make API step consistent

---

src/tree/CosmosDBAccountWizard/CosmosDBAccountCreateStep.ts
src/utils/localize.ts

Add generic 'time remaining' message to account creation notification

---

src/tree/AttachedAccountsTreeItem.ts
src/utils/localize.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/994

Don't allow trailing whitespace in connection strings

---

src/postgres/tree/PostgresDatabaseTreeItem.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1389

Remove servername requirement from Postgres username prompt

---

src/postgres/getPostgresCredentials.ts
src/postgres/tree/PostgresDatabaseTreeItem.ts

Combining https://github.com/microsoft/vscode-cosmosdb/pull/1395 and https://github.com/microsoft/vscode-cosmosdb/pull/1396

Update warning and when to prompt for Postgres credentials

---

package.json
src/postgres/commands/deletePostgresTable.ts
src/postgres/commands/registerPostgresCommands.ts
src/postgres/tree/PostgresDatabaseTreeItem.ts
src/postgres/tree/PostgresTableTreeItem.ts
src/postgres/tree/PostgresTablesTreeItem.ts

Delete Postgres Table

---

src/docdb/tree/DocDBDatabaseTreeItemBase.ts

Changed minThroughputPartitioned so that RU can be specified from 400 even in non-Fixed state.

 Change the minimum database throughput value from 400

---

package.json
src/postgres/commands/deletePostgresFunction.ts
src/postgres/commands/registerPostgresCommands.ts
src/postgres/tree/PostgresFunctionTreeItem.ts

Related to https://github.com/microsoft/vscode-cosmosdb/issues/1407

Add support for deleting Postgres functions

---

src/postgres/IPostgresProceduresQueryRow.ts
src/postgres/tree/PostgresFunctionTreeItem.ts
src/postgres/tree/PostgresFunctionsTreeItem.ts

Setting up this interface for use with stored procedures too
Related to https://github.com/microsoft/vscode-cosmosdb/issues/1407

Move query row interface to its own file

---

src/postgres/tree/PostgresDatabaseTreeItem.ts
src/postgres/tree/PostgresFunctionsTreeItem.ts

From https://github.com/microsoft/vscode-cosmosdb/pull/1427#pullrequestreview-399393915

Update logic for duplicate Postgres resources

---

src/postgres/commands/setPostgresCredentials.ts
src/postgres/tree/PostgresServerTreeItem.ts

I missed this when I merged the rebrand changes with master

Fix Postgres service name

---

src/postgres/tree/PostgresDatabaseTreeItem.ts

Add 'Connected' description to Postgres database

---

src/postgres/tree/PostgresServerTreeItem.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1446

Delete credentials when deleting a Postgres server

---

package.json
src/postgres/commands/executePostgresQuery.ts
src/postgres/commands/registerPostgresCommands.ts
src/postgres/tree/PostgresDatabaseTreeItem.ts

I added 'returned fields' to the query output. Here's an example of querying a table followed by creating a function:

Add support for executing Postgres queries

---

.azure-pipelines/common/build.yml
package-lock.json
package.json
src/utils/InteractiveChildProcess.ts
test/mongoShell.test.ts

Related to https://github.com/microsoft/vscode-azurefunctions/issues/2103

Bump min version of VS Code to 1.40.0 and Node.js to 12.0.0

---

package.json

Had a little merge master mishap

Add 'PostgreSQL' category to 'Create Function Query...' command

---

package.json
src/postgres/commands/checkAuthentication.ts
src/postgres/commands/copyConnectionString.ts
src/postgres/commands/executePostgresQuery.ts
src/postgres/commands/registerPostgresCommands.ts
src/postgres/tree/PostgresDatabaseTreeItem.ts

Format: "postgres://user:password@host:port/dbName"

copyConnectionString command for Postgres Database

---

package-lock.json
package.json

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1463

Pull up 💪 ui package 📦

---

src/docdb/tree/DocDBDatabaseTreeItemBase.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/806

Add placeholder for partition key input

---

src/mongo/tree/MongoCollectionTreeItem.ts

Before
After
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/636

Error handling for mongo doc tree items

---

src/postgres/commands/PostgresAccountWizard/PostgresServerNameStep.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1505

Update duplicate server name error

---

src/postgres/commands/executePostgresQuery.ts
src/postgres/tree/PostgresDatabaseTreeItem.ts
src/postgres/tree/PostgresFunctionTreeItem.ts
src/postgres/tree/PostgresFunctionsTreeItem.ts

Not ending connections once we were done with them was causing access issues. 
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1504

Cleanup Postgres connections

---

src/AzureDBExperiences.ts
src/tree/AttachedAccountsTreeItem.ts

Related to https://github.com/microsoft/vscode-cosmosdb/issues/1498#issuecomment-634195234

Remove Postgres option from 'Attach Database Account...'

---

src/table/tree/TableAccountTreeItem.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1516

Table accounts shouldn't be parent nodes

---

src/postgres/commands/PostgresAccountWizard/PostgresServerFirewallStep.ts
src/postgres/commands/configurePostgresFirewall.ts

Getting the public IP sometimes takes forever so I added a progress notification.
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1497

Add progress notification when getting public IP

---

src/postgres/commands/PostgresAccountWizard/PostgresServerSetCredentialsStep.ts
src/postgres/commands/PostgresAccountWizard/PostgresServerSetFirewallStep.ts

Add Firewall and Credentials setup notifications to log

---

package.json
src/constants.ts
src/postgres/commands/createPostgresFunctionQuery.ts
src/postgres/commands/openPostgresFunction.ts
src/postgres/commands/registerPostgresCommands.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1495

Use 'psql' file extension for Postgres

---

src/postgres/commands/PostgresAccountWizard/PostgresServerCreateStep.ts
src/postgres/commands/createPostgresDatabase.ts
src/postgres/commands/deletePostgresDatabase.ts
src/postgres/commands/deletePostgresFunction.ts
src/postgres/commands/deletePostgresServer.ts
src/postgres/commands/deletePostgresTable.ts
src/tree/SubscriptionTreeItem.ts

Success notifications and log output for postgres operations

---

CHANGELOG.md

Markdown formatting in VS Code was funky (peep the "Fixed" subheading). Shoutout to @neelip for finding this problem
Old -> New

Fix CHANGELOG formatting in VS Code

---

src/mongo/MongoScrapbook.ts

I'm a little hesitant to remove the "Unrecognized node type encountered" part because it's part of the error message and does accurately describe what the problem is. I shuffled around the error message to hopefully make it more readable.
| old | new |
| - | - |
| <img width="387" alt="Screen Shot 2020-06-03 at 11 00 30 AM" src="https://user-images.githubusercontent.com/22795803/83671368-74637880-a589-11ea-8c5b-63867fd74d16.png"> | <img width="387" alt="Screen Shot 2020-06-03 at 10 54 24 AM" src="https://user-images.githubusercontent.com/22795803/83671245-37978180-a589-11ea-9efa-28be6df3d940.png"> |
Fixes https://github.com/microsoft/vscode-cosmosdb/issues/934

Update error when executing mongo command

---

src/postgres/tree/PostgresDatabaseTreeItem.ts
src/postgres/tree/PostgresFunctionsTreeItem.ts
src/postgres/tree/PostgresResourcesTreeItemBase.ts
src/postgres/tree/PostgresTablesTreeItem.ts

Setting up for stored procedures support

Move shared Postgres code to base class

---

src/extension.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1251

Show error message when attempting to connect to emulator on Mac

---

package-lock.json
package.json

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1507

Bump UI 👊👁

---

src/postgres/commands/createPostgresServer/IPostgresServerWizardContext.ts
src/postgres/commands/createPostgresServer/steps/PostgresServerConfirmPWStep.ts
src/postgres/commands/createPostgresServer/steps/PostgresServerCreateStep.ts
src/postgres/commands/createPostgresServer/steps/PostgresServerCredPWStep.ts
src/postgres/commands/createPostgresServer/steps/PostgresServerCredUserStep.ts
src/postgres/commands/createPostgresServer/steps/PostgresServerFirewallStep.ts
src/postgres/commands/createPostgresServer/steps/PostgresServerNameStep.ts
src/postgres/commands/createPostgresServer/steps/PostgresServerSetCredentialsStep.ts
src/postgres/commands/createPostgresServer/steps/PostgresServerSetFirewallStep.ts
src/tree/AzureDBAPIStep.ts
src/tree/SubscriptionTreeItem.ts

Updating to match [this pattern](https://github.com/microsoft/vscode-cosmosdb/pull/1568#discussion_r439007606)

Update Postgres server wizard folder structure

---

package-lock.json
package.json
src/mongo/MongoScrapbook.ts

Matches behavior from before I changed the editors in https://github.com/microsoft/vscode-cosmosdb/pull/1572
Depends on https://github.com/microsoft/vscode-azuretools/pull/750

Show in next view column when executing mongo commands

---

src/DatabasesFileSystem.ts

From https://github.com/microsoft/vscode-azuretools/pull/749#issuecomment-648331257

Return a new collection node if one doesn't exist

---

src/mongo/MongoScrapbook.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/958

Clean up error reporting in MongoScrapbook.ts

---

src/mongo/tree/MongoDatabaseTreeItem.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/706

Throw a better error if the emulator isn't started (Mongo shell)

---

src/postgres/commands/createPostgresDatabase.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1543

Connect Postgres database after its created

---

src/tree/AttachedAccountsTreeItem.ts

Going off of [this comment](https://github.com/microsoft/vscode-cosmosdb/issues/974#issuecomment-577924102), I took a look at keytar to see if we could cut down on its usage. We seem to be using it for the bare minimum - just for attached account connection strings and Postgres passwords. So I just refactored to make the Postgres and attached account implementations match more closely.

Switch to keytar environment variable

---

src/commands/deleteCosmosDBAccount.ts

Log info for deleting cosmos account

---

extension.bundle.ts
main.js
src/mongo/connectToMongoClient.ts
test/mongoConnectionStrings.test.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1241

Fix self signed certificate error when connecting to Mongo emulator

---

src/postgres/commands/configurePostgresFirewall.ts

Add "Adding firewall..." message to output log

---

src/docdb/registerDocDBCommands.ts

Add Attached Accounts option to SQL - Create Database

---

package.json

Update group for "New Mongo Scrapbook" command

---

src/docdb/registerDocDBCommands.ts
src/extension.ts
src/graph/registerGraphCommands.ts
src/mongo/registerMongoCommands.ts
src/postgres/commands/deletePostgresDatabase.ts
src/postgres/commands/deletePostgresFunction.ts
src/postgres/commands/deletePostgresServer.ts
src/postgres/commands/deletePostgresStoredProcedure.ts
src/postgres/commands/deletePostgresTable.ts

Suppress "Create..." option for delete commands tree item picker

---

src/AzureDBExperiences.ts
src/mongo/registerMongoCommands.ts
src/tree/SubscriptionTreeItem.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1517

Automatically select Mongo experience when creating an account via 'connectMongoDB'

---

src/AzureDBExperiences.ts
src/tree/AttachedAccountsTreeItem.ts

Update attach database prompt - naming changes of API options

---

src/extension.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1619

Clear un-uploaded changes to Mongo & DocDB documents before opening

---

src/postgres/postgresConnectionStrings.ts

Removes redundant decoding URI code

---

package-lock.json
package.json
src/postgres/commands/copyConnectionString.ts
src/postgres/commands/registerPostgresCommands.ts
src/postgres/getClientConfig.ts
src/postgres/postgresConnectionStrings.ts
src/postgres/tree/PostgresDatabaseTreeItem.ts
src/postgres/tree/PostgresServerTreeItem.ts
src/tree/SubscriptionTreeItem.ts

Fix for Expected non-null or undefined 'username' error

---

src/postgres/commands/createPostgresServer/steps/PostgresServerCredUserStep.ts

Fix postgres username validation

---

src/postgres/commands/createPostgresServer/IPostgresServerWizardContext.ts
src/postgres/commands/createPostgresServer/steps/PostgresServerCreateStep.ts
src/postgres/commands/createPostgresServer/steps/PostgresServerCredPWStep.ts
src/postgres/commands/createPostgresServer/steps/PostgresServerCredUserStep.ts
src/postgres/commands/createPostgresServer/steps/PostgresServerSetCredentialsStep.ts
src/tree/SubscriptionTreeItem.ts

Fixes invalid characters error for valid postgres inputs

---

src/postgres/getPostgresProcedureQueryRows.ts
src/postgres/tree/PostgresDatabaseTreeItem.ts
src/postgres/tree/PostgresServerTreeItem.ts

Enable display of storeProcedures for attached accounts

---

package-lock.json
package.json

Reverted to older version of pg-structure to support displaying Postgres Table

---

src/postgres/commands/createPostgresServer/steps/PostgresServerCreateStep.ts

Set vcore to default for Postgres Create

---

package-lock.json
package.json

Updated "mongodb" package

---

src/tree/CosmosDBAccountWizard/CosmosDBAccountNameStep.ts

Without this fix, all account names in the cosmos create scenario are getting a "Account name ... is not available."

Fixes checkNameExists issue that occurred with PR 1730

---

src/graph/gremlinEndpoints.ts
test/nightly/azureResourceGraph.test.ts

Fixes failing graph related Nightly Tests

Fixes to Graph Treeview Issues

---

src/postgres/commands/createPostgresServer/steps/PostgresServerCredUserStep.ts

Fix username validation for restricted usernames

---

src/docdb/getCosmosClient.ts
src/docdb/tree/DocDBAccountTreeItemBase.ts
test/nightly/azureResourceSQL.test.ts

Fix ssl verification issue with new sdk

---

src/mongo/tree/MongoCollectionTreeItem.ts

Fix for Upload to Mongo Collection issue

---

package-lock.json

https://dev.azure.com/ms-azuretools/AzCode/_componentGovernance/89503/alert/3626169?typeId=543873
`Ajv` depends on recent package updates.

Update "ajv" package to fix security alert

---

src/mongo/mongoConnectionStrings.ts

Removed deprecated properties Server, ReplSet, Mongos of "mongodb" sdk

---

src/tree/AttachedAccountsTreeItem.ts

Remove canConnectToLocalMongoDB function

---

CHANGELOG.md
NOTICE.html
package-lock.json
package.json

RC for 0.15.1

---

src/postgres/commands/createPostgresQuery/validateIdentifier.ts

Add max length validation for Postgres Functions & StoredProcedures names

---

src/postgres/commands/executePostgresQuery.ts

Refresh Postgres Functions tree after executing query

---

src/postgres/commands/createPostgresQuery/function/steps/FunctionQueryCreateStep.ts

Fixed case issue for Postgres Functions

---

src/postgres/commands/createPostgresQuery/storedProcedure/steps/StoredProcedureQueryCreateStep.ts

Fixed case issue for Postgres Stored Procedures

---

package.json

Grouped Context Menus

---

src/postgres/tree/PostgresFunctionTreeItem.ts

Fix Delete Function issue with WrapArgInQuotes()

---

src/tree/AzureDBAPIStep.ts
src/tree/SubscriptionTreeItem.ts

Added VerifyProviderStep to "Create Postgres Server"

---

src/docdb/tree/DocDBStoredProceduresTreeItem.ts

Fixes #1789, Fixes #1773 and Fixes #1719

Update SQL Stored Procedure Name Validation

---

package.json
src/extension.ts

Use "Report Issue" command

---

src/postgres/commands/createPostgresServer/steps/PostgresServerNameStep.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountNameStep.ts

Related to https://github.com/microsoft/vscode-azuretools/pull/824

Use valuesToMask for server name

---

CHANGELOG.md
gulpfile.ts
package-lock.json
package.json
resources/azure.svg

Depends on https://github.com/microsoft/vscode-azuretools/pull/852

Depend on Resource Groups extension

---

.vscode/extensions.json
README.md

Already did it in most repos yesterday, just not the first two.

Add resource groups extension to recommended for workspace

---

package-lock.json
package.json
src/tree/AttachedAccountsTreeItem.ts

Bump shared packages

---

.azure-pipelines/common/package.yml
.azure-pipelines/compliance/CredScanSuppressions.json
.azure-pipelines/compliance/compliance.yml
.azure-pipelines/main.yml

Same as microsoft/vscode-azurefunctions#2769

Add AntiMalware Scanner to build

---

package-lock.json
package.json

Reverts microsoft/vscode-cosmosdb#1841
Reason: Problem with package-lock.json

Revert "Bump extension version to 0.16.1-alpha"

---

package.json
src/docdb/getCosmosClient.ts
src/extensionVariables.ts

Support for CosmosDB's enableEndpointDiscovery as requested in: #1857

Support for CosmosDB's enableEndpointDiscovery #1857

---

src/constants.ts
src/docdb/tree/DocDBAccountTreeItemBase.ts
src/docdb/tree/DocDBDatabaseTreeItemBase.ts
src/tree/AzureDBAPIStep.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountCapacityStep.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountCreateStep.ts
src/tree/CosmosDBAccountWizard/ICosmosDBWizardContext.ts
src/utils/openUrl.ts

Added serverless capacity model to CosmosDB create

---

package-lock.json
package.json
src/docdb/tree/DocDBAccountTreeItem.ts
src/docdb/tree/DocDBAccountTreeItemBase.ts
src/docdb/tree/DocDBDocumentsTreeItem.ts
src/docdb/tree/DocDBStoredProceduresTreeItem.ts
src/graph/tree/GraphAccountTreeItem.ts
src/graph/tree/GraphTreeItem.ts
src/mongo/tree/MongoAccountTreeItem.ts
src/postgres/tree/PostgresFunctionsTreeItem.ts
src/postgres/tree/PostgresServerTreeItem.ts
src/postgres/tree/PostgresStoredProceduresTreeItem.ts
src/postgres/tree/PostgresTablesTreeItem.ts
src/table/tree/TableAccountTreeItem.ts
src/tree/AttachedAccountsTreeItem.ts

Similar changes as [#2087](https://github.com/microsoft/vscode-azureappservice/pull/2087)

Improving user data masking

---

package-lock.json
package.json
src/DatabasesFileSystem.ts
src/commands/deleteCosmosDBAccount.ts
src/docdb/tree/DocDBAccountTreeItemBase.ts
src/docdb/tree/DocDBCollectionTreeItem.ts
src/docdb/tree/DocDBDatabaseTreeItemBase.ts
src/docdb/tree/DocDBDocumentTreeItem.ts
src/docdb/tree/DocDBDocumentsTreeItem.ts
src/docdb/tree/DocDBStoredProcedureTreeItem.ts
src/docdb/tree/DocDBStoredProceduresTreeItem.ts
src/graph/tree/GraphCollectionTreeItem.ts
src/graph/tree/GraphTreeItem.ts
src/mongo/tree/MongoAccountTreeItem.ts
src/mongo/tree/MongoCollectionTreeItem.ts
src/mongo/tree/MongoDatabaseTreeItem.ts
src/mongo/tree/MongoDocumentTreeItem.ts
src/postgres/commands/configurePostgresFirewall.ts
src/postgres/commands/deletePostgresDatabase.ts
src/postgres/commands/deletePostgresFunction.ts
src/postgres/commands/deletePostgresServer.ts
src/postgres/commands/deletePostgresStoredProcedure.ts
src/postgres/commands/deletePostgresTable.ts
src/postgres/commands/enterPostgresCredentials.ts
src/postgres/tree/PostgresDatabaseTreeItem.ts
src/postgres/tree/PostgresServerTreeItem.ts
src/tree/AttachedAccountsTreeItem.ts
test/runTest.ts

Bump shared packages and add 'stepName'.

Funnel telemetry - updates

---

src/postgres/tree/PostgresDatabaseTreeItem.ts

Fixes #1913 
After testing, found out that the issue is not specific to Windows, it occurs with all OS types.

Correction to last release: ETIMEDOUT issue

---

CHANGELOG.md
src/postgres/commands/configurePostgresFirewall.ts
src/utils/randomUtils.ts

Make Postgres Firewall Rule label unique

---

.vscodeignore

Reduced size of vsix from ~12.5 MB to ~2.5 MB

Exclude gifs from being added to vsix

---

package-lock.json

This fixes the axios CG alert [CVE-2021-3749](https://dev.azure.com/ms-azuretools/AzCode/_componentGovernance/89503/alert/5966247?typeId=4623061)

Run "npm audit fix --production"

---

.azure-pipelines/common/sbom.yml
.azure-pipelines/main.yml
src/postgres/postgresConnectionStrings.ts

Hey @alexweininger,
This fixes: https://github.com/microsoft/vscode-cosmosdb/issues/1952
Also, I have committed the TS file. Do we need to commit the `package-lock.json` too? Please let me know if that's the case as I am very very new to JS/TS. I tried the extension and it works perfectly with single quotes as expected.

Add Single Quotes for PSQL Connection String Password

---

package-lock.json
package.json
src/AzureDBExperiences.ts
src/commands/importDocuments.ts
src/constants.ts
src/docdb/registerDocDBCommands.ts
src/extension.ts
src/graph/registerGraphCommands.ts
src/mongo/registerMongoCommands.ts
src/postgres/commands/configurePostgresFirewall.ts
src/postgres/commands/connectPostgresDatabase.ts
src/postgres/commands/copyConnectionString.ts
src/postgres/commands/createPostgresDatabase.ts
src/postgres/commands/deletePostgresDatabase.ts
src/postgres/commands/deletePostgresFunction.ts
src/postgres/commands/deletePostgresServer.ts
src/postgres/commands/deletePostgresStoredProcedure.ts
src/postgres/commands/deletePostgresTable.ts
src/postgres/commands/enterPostgresCredentials.ts
src/postgres/commands/executePostgresQuery.ts
src/postgres/commands/openPostgresFunction.ts
src/postgres/commands/openPostgresStoredProcedure.ts
src/resolver/ResolvedDatabaseAccountResource.ts

Depends on https://github.com/microsoft/vscode-azuretools/pull/1146 and https://github.com/microsoft/vscode-azureresourcegroups/pull/221

Replace showTreeItemPicker with pickAppResource

---

package-lock.json
package.json
src/postgres/commands/configurePostgresFirewall.ts
src/postgres/tree/PostgresDatabaseTreeItem.ts

Fixes #1982, #1983, #1984, and #1986

Fix context menus, and configure firewall command

---

.vscode/launch.json
package-lock.json
package.json

Depends on https://github.com/microsoft/vscode-azureresourcegroups/pull/242
Part of fixing https://github.com/microsoft/vscode-azureresourcegroups/issues/214

Add detail to create command

---

package-lock.json
package.json
src/commands/api/pickTreeItem.ts
src/constants.ts

Fixes https://github.com/microsoft/vscode-azureappservice/issues/2229
Fixes https://github.com/microsoft/vscode-azureappservice/issues/2226

Fix pickTreeItem API command

---

package-lock.json
package.json
src/extension.ts
src/resolver/DatabaseWorkspaceProvider.ts

Fixes attaching a database account before the workspace view is opened.

Fix attaching database account

---

package-lock.json
package.json
src/resolver/AppResolver.ts

Build has been broken since #2010

Fix nullish subNode

---

package-lock.json
package.json

Remove duplicate refresh context menu item

---

package-lock.json
package.json
src/tree/SubscriptionTreeItem.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/2013

Refresh tree after creating a server

---

package-lock.json
package.json
src/commands/deleteDatabaseAccount/deleteDatabaseAccount.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/2019

Remove $ from delete confirmation message

---

package-lock.json
package.json

Remove extra refresh context menu item from graph db servers

---

package-lock.json
package.json
src/extension.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/2020

Include gremlin and sql accounts in commands

---

package-lock.json
package.json
src/extension.ts

Fixes a bug that was similar to https://github.com/microsoft/vscode-azurestorage/issues/1044

Hack into the unknown

---

CHANGELOG.md
NOTICE.html
package-lock.json
package.json

- Bump version
- Update CHANGELOG
- Update NOTICE

Release v0.19.1 prep

---

src/commands/importDocuments.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/2038

Change filter for treeItemPicker

---

package-lock.json
package.json
src/docdb/registerDocDBCommands.ts
src/extension.ts
src/graph/registerGraphCommands.ts
src/mongo/registerMongoCommands.ts
src/postgres/commands/registerPostgresCommands.ts

Made changes listed [here](https://github.com/microsoft/vscode-azureresourcegroups/wiki/Upgrading-Extensions-for-V2-Compatibility).

Upgrade databases extension for V2 compatability

---

.eslintignore
gulpfile.ts
package-lock.json
package.json
test/global.test.ts
test/mongoShell.test.ts
test/nightly/global.resource.test.ts
test/runTest.ts

I commented out most of the testing code for Cosmos because it's very specific to Cosmos where as a lot of the other extensions had shared/duplicated code.
Had to upgrade the test/dev packages to get the Mac builds working as well.
Based off of this PR: https://github.com/microsoft/vscode-azurefunctions/pull/3275/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

Skip test suite to enable CodeQL build

---

package-lock.json
package.json
src/DatabasesFileSystem.ts

Picking up changes made to `AzExtTreeFileSystem` in https://github.com/microsoft/vscode-azuretools/pull/1257

Use updated AzExtTreeFileSystem

---

CHANGELOG.md
package-lock.json
package.json

Couldn't get the notice generation to work...

Prep for v0.19.3 release

---

package.json

Working towards https://github.com/microsoft/vscode-azureresourcegroups/issues/673

Add actions submenu to workspace view title

---

extension.bundle.ts
src/postgres/commands/checkAuthentication.ts
src/postgres/tree/PostgresDatabaseTreeItem.ts
src/postgres/tree/PostgresServerTreeItem.ts
src/resolver/ResolvedPostgresServerResource.ts
src/utils/getIp.ts
test/util/getIp.test.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/2166
Explicitly check for firewall rules instead of waiting for a timeout.

Fix firewall error being handled as missing credential

---

src/graph/tree/GraphTreeItem.ts

Mitigates https://github.com/microsoft/vscode-cosmosdb/issues/2086, https://github.com/microsoft/vscode-cosmosdb/issues/1967
I plan to use this for the forward link: https://learn.microsoft.com/azure/cosmos-db/gremlin/visualization-partners

Stop attempting to use CosmosDBGraph extension

---

src/docdb/tree/DocDBDocumentTreeItem.ts
src/docdb/tree/DocDBUtils.ts
test/unit/DocDBUtils.test.ts

Further mitigates https://github.com/microsoft/vscode-cosmosdb/issues/1732

Replace + in DocDB document id to whitespace

---

src/docdb/tree/DocDBAccountTreeItemBase.ts
src/mongo/tree/MongoAccountTreeItem.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/2061

Invalidate new database names containing '='

---

src/docdb/tree/DocDBDatabaseTreeItemBase.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/1865

Improve throughput validation message

---

src/docdb/tree/DocDBDatabaseTreeItemBase.ts
src/graph/tree/GraphDatabaseTreeItem.ts

fixes https://github.com/microsoft/vscode-cosmosdb/issues/1896

Customize partition key validation rule for Gremlin DB

---

src/commands/deleteDatabaseAccount/deleteCosmosDBAccount.ts

Fixes https://github.com/microsoft/vscode-cosmosdb/issues/2025

Respect suppressNotification when deleting CosmosDBAccount

---

package.json
src/postgres/commands/checkAuthentication.ts
src/postgres/commands/registerPostgresCommands.ts
src/postgres/tree/ClientConfigFactory.ts
src/postgres/tree/PostgresDatabaseTreeItem.ts
src/postgres/tree/PostgresServerTreeItem.ts

resolves https://github.com/microsoft/vscode-cosmosdb/issues/2177

Show inline action when using password

---

src/postgres/commands/registerPostgresCommands.ts

The forward link has been created. I forget to push this commit.

Remove todo that has been done

---

README.md

Those features have been removed.

Remove description of graph related features

---

package.json

fixes https://github.com/microsoft/vscode-cosmosdb/issues/2192
When showing the password inline action, the context value of the database nodes are "postgresDatabase;usesPassword".

Fix context menu command condition

---

src/tree/AzureDBAPIStep.ts
src/tree/CosmosDBAccountWizard/CosmosDBAccountCreateStep.ts
src/tree/CosmosDBAccountWizard/ICosmosDBWizardContext.ts
src/tree/CosmosDBAccountWizard/MongoDBVersionStep.ts

resolves https://github.com/microsoft/vscode-cosmosdb/issues/1999

Allow selecting mongo version when creating database server

---

package.json
src/docdb/registerDocDBCommands.ts
src/docdb/tree/DocDBStoredProcedureTreeItem.ts

There were work items for this:
https://github.com/microsoft/vscode-cosmosdb/issues/2066
https://github.com/microsoft/vscode-cosmosdb/issues/896

feature: CosmosDB execute stored procedure

---

src/postgres/commands/executePostgresQueryInDocument.ts
src/postgres/commands/registerPostgresCommands.ts
src/postgres/commands/showPasswordlessWiki.ts

Reorganize code so that Postgres command registration is separated from implementations.

chore: reorganize Postgres command registration

---

src/docdb/commands/connectNoSqlContainer.ts
src/docdb/commands/createDocDBCollection.ts
src/docdb/commands/createDocDBDatabase.ts
src/docdb/commands/createDocDBDocument.ts
src/docdb/commands/createDocDBStoredProcedure.ts
src/docdb/commands/createDocDBTrigger.ts
src/docdb/commands/deleteDocDBCollection.ts
src/docdb/commands/deleteDocDBDatabase.ts
src/docdb/commands/deleteDocDBDocument.ts
src/docdb/commands/deleteDocDBStoredProcedure.ts
src/docdb/commands/deleteDocDBTrigger.ts
src/docdb/commands/executeDocDBStoredProcedure.ts
src/docdb/commands/executeNoSqlQuery.ts
src/docdb/commands/getNoSqlQueryPlan.ts
src/docdb/commands/openStoredProcedure.ts
src/docdb/commands/openTrigger.ts
src/docdb/commands/pickDocDBAccount.ts
src/docdb/commands/writeNoSqlQuery.ts
src/docdb/registerDocDBCommands.ts

Reorganize code so that DocDB command registration is separated from command implementations.

chore: reorganize DocDB command registration

---

src/mongo/commands/connectMongoDatabase.ts
src/mongo/commands/createMongoCollection.ts
src/mongo/commands/createMongoDatabase.ts
src/mongo/commands/createMongoDocument.ts
src/mongo/commands/createMongoScrapbook.ts
src/mongo/commands/deleteMongoCollection.ts
src/mongo/commands/deleteMongoDatabase.ts
src/mongo/commands/deleteMongoDocument.ts
src/mongo/commands/executeAllMongoCommand.ts
src/mongo/commands/executeMongoCommand.ts
src/mongo/commands/launchMongoShell.ts
src/mongo/commands/openMongoCollection.ts
src/mongo/commands/pickMongo.ts
src/mongo/registerMongoCommands.ts

Reorganize code so that MongoDB command registration is separate from command implementations.

chore: reorganize MongoDB command registration

---

package.json

fixes: https://github.com/microsoft/vscode-cosmosdb/issues/2151

fix: Workspace submenu action icon

---

src/postgres/tree/PostgresServerTreeItem.ts

fixes: https://github.com/microsoft/vscode-cosmosdb/issues/2224

fix: Create Postgres Database

---

package-lock.json
package.json
src/postgres/abstract/AbstractPostgresClient.ts
src/postgres/commands/createPostgresServer/steps/PostgresServerCreateStep.ts
src/utils/azureClients.ts

resolves: https://github.com/microsoft/vscode-cosmosdb/issues/2195

chore: Update postgres flexible sdk

---

src/docdb/commands/deleteDocDBDatabase.ts
src/mongo/commands/deleteMongoDatabase.ts

resolves: https://github.com/microsoft/vscode-cosmosdb/issues/1863

chore: Log successful CosmosDB deletion

---

src/docdb/tree/DocDBTriggersTreeItem.ts

fixes: https://github.com/microsoft/vscode-cosmosdb/issues/2262

fix: Add trigger creation placeholders

---

src/docdb/commands/deleteDocDBStoredProcedure.ts
src/docdb/registerDocDBCommands.ts
src/docdb/tree/DocDBStoredProceduresTreeItem.ts

fixes: https://github.com/microsoft/vscode-cosmosdb/issues/2261

fix: Delete DocDB stored procedure

---

package.json
src/docdb/commands/getNoSqlQueryPlan.ts

fixes: https://github.com/microsoft/vscode-cosmosdb/issues/2271

fix: Fix getting NoSQL query plan from command palette

---

CHANGELOG.md
NOTICE.html
package-lock.json
package.json

https://github.com/microsoft/azcode-internal/issues/115

chore: Prepare 0.21.0 release

---

package-lock.json
package.json

https://github.com/microsoft/azcode-internal/issues/115

chore: Post 0.21.0 release update

---

package-lock.json
package.json
src/commands/api/DatabaseAccountTreeItemInternal.ts
src/docdb/NoSqlCodeLensProvider.ts
src/docdb/commands/connectNoSqlContainer.ts
src/docdb/commands/executeNoSqlQuery.ts
src/docdb/commands/getNoSqlQueryPlan.ts
src/docdb/getCosmosClient.ts
src/docdb/tree/DocDBAccountTreeItemBase.ts
src/docdb/tree/DocDBDocumentTreeItem.ts
src/docdb/tree/IDocDBTreeRoot.ts
src/graph/tree/GraphAccountTreeItem.ts
src/tree/AttachedAccountsTreeItem.ts
src/tree/SubscriptionTreeItem.ts

resolves: https://github.com/microsoft/vscode-cosmosdb/issues/2205
This PR duplicates some internal implementation of the auth package as the workaround to its limited export.

Enable CosmosDB OAuth support

---

CHANGELOG.md
NOTICE.html
package-lock.json
package.json
src/tree/SubscriptionTreeItem.ts

related to: https://github.com/microsoft/azcode-internal/issues/125

chore: Prepare 0.22.0 release

---

package-lock.json
package.json
src/tree/AttachedAccountsTreeItem.ts

Includes new updates for telemetry via the utils package

Upgrade the utils and dev package

---

src/docdb/commands/createDocDBDocument.ts
src/docdb/commands/createDocDBStoredProcedure.ts
src/docdb/commands/createDocDBTrigger.ts
src/docdb/commands/deleteDocDBDocument.ts
src/docdb/commands/deleteDocDBStoredProcedure.ts
src/docdb/commands/deleteDocDBTrigger.ts
src/docdb/commands/executeDocDBStoredProcedure.ts
src/docdb/commands/openStoredProcedure.ts
src/docdb/commands/openTrigger.ts
src/docdb/tree/DocDBStoredProcedureTreeItem.ts
src/mongo/commands/connectMongoDatabase.ts
src/mongo/commands/createMongoDocument.ts
src/mongo/commands/createMongoScrapbook.ts
src/mongo/commands/deleteMongoDocument.ts
src/mongo/commands/executeAllMongoCommand.ts
src/mongo/commands/executeMongoCommand.ts
src/mongo/commands/openMongoCollection.ts

This PR fixes ESLint warnings to get cleaner PR reviews.

Fix ESLint warnings

---

package.json
src/panels/QueryEditorTab.ts
src/webviews/QueryEditor/QueryEditorContext.tsx
src/webviews/QueryEditor/QueryPanel/QueryMonaco.tsx
src/webviews/QueryEditor/QueryPanel/QueryToolbar.tsx
src/webviews/QueryEditor/ResultPanel/ResultPanel.tsx
src/webviews/QueryEditor/ResultPanel/ResultTab.tsx
src/webviews/QueryEditor/ResultPanel/ResultToolbar.tsx
src/webviews/QueryEditor/ResultPanel/StatsTab.tsx
src/webviews/utils/convertors.ts
src/webviews/utils/index.ts
webpack.config.ext.js
webpack.config.views.js

This pull request includes several changes to improve the functionality and maintainability of the Query Editor. The most important changes include updates to the `saveFile` method to accept an additional parameter, refactoring of the `ResultPanel` and `ResultTab` components, and updates to the `package.json` scripts.
* [`src/panels/QueryEditorTab.ts`](diffhunk://#diff-481b7c7d679172d98c1a1aabd3cda871ebd10b3d747f2afa2ea1dfc3245842b7L181-R183): Updated the `saveFile` method to accept an additional `ext` parameter, allowing for more flexible file saving options. [[1]](diffhunk://#diff-481b7c7d679172d98c1a1aabd3cda871ebd10b3d747f2afa2ea1dfc3245842b7L181-R183) [[2]](diffhunk://#diff-481b7c7d679172d98c1a1aabd3cda871ebd10b3d747f2afa2ea1dfc3245842b7L243-R246)
* …

chore: Extension loads json and css plugins in production mode

---

.azure-pipelines/release.yml

After merging I can create the pipeline in Azure DevOps.

Add release pipeline

---

CHANGELOG.md
README.md

- New release info
- Fixes README typos

chore: Adds info about next release

---

package-lock.json
package.json
src/docdb/getCosmosClient.ts
src/docdb/session/QuerySession.ts
src/docdb/types/queryResult.ts
src/webviews/QueryEditor/ResultPanel/ResultPanelToolbar.tsx
src/webviews/QueryEditor/state/QueryEditorContextProvider.tsx
src/webviews/QueryEditor/state/QueryEditorState.tsx
src/webviews/Timer.tsx

feat: Timer shows instead of record counter while query is executing

---

src/docdb/session/DocumentSession.ts
src/docdb/session/QuerySession.ts
src/docdb/session/QuerySessionResult.ts
src/docdb/types/queryResult.ts
src/utils/convertors.ts
src/utils/document.ts
src/utils/nonNull.ts
src/webviews/Document/DocumentPanel.tsx
src/webviews/QueryEditor/ResultPanel/ResultTabToolbar.tsx
src/webviews/utils/index.ts

- Fixes issue with non-unique id
- Fixes issue that document is not found when it opens in view tab. Edit buttons are displayed only if query is `SELECT * ...`

fix: All records have unique Id for table view.

---

package-lock.json
package.json
src/webviews/mongoClusters/collectionView/collectionView.scss
src/webviews/mongoClusters/collectionView/components/QueryEditor.tsx

…t download. we don't use this dependency anymore

vCore: bugfix: stopped downloading obsolete fonts in vCore webviews

---

src/utils/convertors.ts

fix: Removing top-level ellipsis in Tree View

---

package-lock.json
package.json

Includes improvements to masking

Upgrade packages to bring in newer telemetry updates

---

src/docdb/session/DocumentSession.ts
src/docdb/session/QuerySession.ts
src/panels/DocumentTab.ts
src/webviews/Document/DocumentPanel.tsx
src/webviews/Document/state/DocumentContextProvider.tsx

fix: Document error messages are shown in VS Code

---

src/tree/CosmosDBAccountWizard/CosmosDBAccountCapacityStep.ts

Improve Capacity Mode selection wording

---

src/docdb/commands/createDocDBDocument.ts

feat: Use webview tab for new Cosmos DB document

---

package.json

Reword RBAC setting description

---

package.json
src/mongoClusters/commands/dropCollection.ts
src/utils/confirmations.ts

The work from prematurely merged https://github.com/microsoft/vscode-cosmosdb/pull/2355 continues here.

 extended confirmation dialog for "risky" operations

---

package-lock.json

This is a rebased version of #2400

Bump dependencies from npm audit

---

package.json

to match attachDatabaseAccount
Fixes #2281

Rename the detachDatabaseAccount command

---

.azure-pipelines/compliance/tsaoptions.json

See https://github.com/microsoft/vscode-azuretools/pull/1823

Add tsaoptions.json

---

package.json

Fix detachDatabaseAccount command category

---

README.md

This pull request includes updates to the `README.md` file for the Azure Databases VS Code Extension. The changes enhance the documentation by providing more detailed descriptions of features, improving readability, and updating information on MongoDB support.

Readme update for better engagement

---

.vscode/extensions.json
.vscode/settings.json

This will hopefully reduce the amount of "Fix Formatting" commits :)

Make VS Code use the projects Prettier config

---

src/mongoClusters/MongoClustersClient.ts
src/mongoClusters/tree/MongoClusterModel.ts
src/tree/mongo/MongoAccountResourceItem.ts

Fixes #2564 
---
This is a small pre-refactoring task, removed unused, closing a long-pending review ticket.

Removed unused emulator/serverless variables in mongo implementation

---

package-lock.json
package.json
package.nls.json
src/docdb/getCosmosClient.ts
src/docdb/utils/managedIdentityUtils.ts
src/docdb/utils/rbacUtils.ts
src/extension.ts
src/extensionVariables.ts
src/tree/docdb/AccountInfo.ts
src/tree/docdb/DocumentDBAccountAttachedResourceItem.ts
src/tree/docdb/DocumentDBAccountResourceItem.ts

This pull request introduces several enhancements and new features to the Cosmos DB authentication process, with a focus on supporting Managed Identity and improving the overall authentication strategy. The most important changes include updating dependencies, adding Managed Identity as an authentication method, and implementing utility functions for Managed Identity.
**Dependency Updates:**
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R143): Added `@azure/identity` version `^4.6.0` to dependencies.
**Authentication Enhancements:**
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L1156-R1180): Added `managedIdentity` as a new authentication method to the configuration.
* …

feat: add support for Managed Identity authentication in Cosmos DB

---

.editorconfig
package-lock.json
package.json
src/utils/convertors.ts
src/utils/document.ts
src/webviews/cosmosdb/QueryEditor/ResultPanel/ResultPanelToolbarOverflow.tsx
src/webviews/cosmosdb/QueryEditor/ResultPanel/ResultTab.tsx
src/webviews/cosmosdb/QueryEditor/ResultPanel/ResultTabViewTree.tsx
src/webviews/cosmosdb/QueryEditor/ResultPanel/StatsTab.tsx

- Calculation functions became async to move them to backend in the future
- Calculation functions break an event loop to avoid UI freeze
- ResultTab shows loading spinner during calculations
- Rollback webpack to 5.95.0 to fix HMR breaking changes
- Add indent size for JSON in .editorconfig
#2624

fix(webview): Maximum call stack size exceeded
